force-app/main/default/objects/Lease__c/Lease__c.object-meta.xml
<CustomObject>
    <label>Lease</label>
    <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Lease Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lease__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leases</relationshipLabel>
    <relationshipName>Leases1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lease__c/fields/cLease_Date_c__c.field-meta.xml
<CustomField>
    <fullName>cLease_Date_c__c</fullName>
    <formula>IF(ISBLANK(Lease_Date__c),&apos;N/A&apos;,TEXT(MONTH(Lease_Date__c))+&quot;/&quot; +TEXT(DAY(Lease_Date__c))+&quot;/&quot; +TEXT(YEAR(Lease_Date__c)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lease Date</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lease__c/fields/cLease_Document_Name__c.field-meta.xml
<CustomField>
    <fullName>cLease_Document_Name__c</fullName>
    <formula>TEXT(Lease_Document_Name__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lease Document Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LeaseListController.cls
public with sharing class LeaseListController {
    @AuraEnabled 
    public static List<Lease__c> getAllLeasesByAccountId(String accountId){
        
            List<Lease__c> leaseList = [SELECT Name, Account__c, cLease_Date_c__c, cLease_Document_Name__c FROM Lease__c WHERE Account__c =:accountId];
            return leaseList;
        
    }

    @AuraEnabled
    public static string getAccountNameFromId(Id accountId){
        
            String name = '';
            name = [SELECT Name FROM Account WHERE Id =: accountId].Name;
            system.debug('account id: ' + accountId);
            system.debug('name:: '+ name);
            return name;
        
    }
}