force-app/main/default/objects/Lease__c/Lease__c.object-meta.xml
<CustomObject>
    <label>Lease</label>
    <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Lease Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lease__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leases</relationshipLabel>
    <relationshipName>Leases1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FilesListControllerTest.cls
@isTest
public class FilesListControllerTest {
	@isTest
    public static void getAllRelatedFilesByIdTest(){
        Account ac = new Account(Name='test');
        insert ac;
        
        Lease__c lease = new Lease__c(Account__c = ac.Id);
        insert lease;
        
        ContentVersion contentVersion_1 = new ContentVersion(
            Title = 'Penguins',
            PathOnClient = 'Penguins.jpg',
            VersionData = Blob.valueOf('Test Content'),
            IsMajorVersion = true
    	);
    	insert contentVersion_1;
        
        ContentVersion contentVersion_2 = [SELECT Id, Title, ContentDocumentId FROM ContentVersion WHERE Id = :contentVersion_1.Id LIMIT 1];
        List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
        lease = [SELECT Id, Name FROM Lease__c LIMIT 1];
        
        ContentDocumentLink contentlink=new ContentDocumentLink();
        contentlink.LinkedEntityId=lease.Id;
        contentlink.contentdocumentid=[select contentdocumentid from contentversion where id =: contentVersion_2.id].contentdocumentid;
        contentlink.ShareType = 'I';
        contentlink.Visibility = 'AllUsers'; 
        
        
        insert contentlink;
        
		FilesListController.getAllRelatedFilesById(lease.Id); 
    }
}