force-app/main/default/objects/Lease__c/Lease__c.object-meta.xml
<CustomObject>
    <label>Lease</label>
    <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Lease Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lease__c/fields/Lease_Document_Name__c.field-meta.xml
<CustomField>
    <fullName>Lease_Document_Name__c</fullName>
    <label>Lease Document Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Combined Lease</fullName>
            </value>
            <value>
                <fullName>Highlighted Lease</fullName>
            </value>
            <value>
                <fullName>Lease Amendment 01</fullName>
            </value>
            <value>
                <fullName>Lease Amendment 02</fullName>
            </value>
            <value>
                <fullName>Lease Amendment 03</fullName>
            </value>
            <value>
                <fullName>Lease Amendment 04</fullName>
            </value>
            <value>
                <fullName>Lease Amendment 05</fullName>
            </value>
            <value>
                <fullName>Lease Amendment 06</fullName>
            </value>
            <value>
                <fullName>Lease Amendment 07</fullName>
            </value>
            <value>
                <fullName>Lease Amendment 08</fullName>
            </value>
            <value>
                <fullName>Lease Amendment 09</fullName>
            </value>
            <value>
                <fullName>Lease Amendment 10</fullName>
            </value>
            <value>
                <fullName>Master Lease</fullName>
            </value>
            <value>
                <fullName>Consent</fullName>
            </value>
            <value>
                <fullName>Lease Commencement Memo</fullName>
            </value>
            <value>
                <fullName>Lease Amendment 01 Commencement Memo</fullName>
            </value>
            <value>
                <fullName>Lease Amendment 02 Commencement Memo</fullName>
            </value>
            <value>
                <fullName>Lease Amendment 03 Commencement Memo</fullName>
            </value>
            <value>
                <fullName>Lease Amendment 04 Commencement Memo</fullName>
            </value>
            <value>
                <fullName>Lease Amendment 05 Commencement Memo</fullName>
            </value>
            <value>
                <fullName>Indemnification Agreement</fullName>
            </value>
            <value>
                <fullName>Coworking/Executive Suite Lease</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lease__c/fields/Lease_Type__c.field-meta.xml
<CustomField>
    <fullName>Lease_Type__c</fullName>
    <label>Lease Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Murray Aronson Document</fullName>
            </value>
            <value>
                <fullName>Original Document</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UploadAttachmentController.cls
public class UploadAttachmentController {
    
    @AuraEnabled 
    public static void setContentDocumentTitleById(String cid, String title, String recordId){
        system.debug('cid::: '+ cid);
        system.debug('title::: '+ title);
        system.debug('recordId::: '+ recordId);
        ContentDocument cd  = [SELECT Id,Title FROM ContentDocument WHERE Id = :cid];
        if(cd != NULL)
        {
			cd.Title = title;
        	update cd;
        }
        if(recordId != null && recordId != ''){
            Lease__c l = new Lease__c(Id=recordId);
            l.Lease_Document_Name__c = title;
            update l;
        }
        
    } 

    @AuraEnabled
    public static Lease__c getLeaseObjectById(String leaseId){
        Lease__c lease = [SELECT Lease_Type__c FROM Lease__c WHERE Id =: leaseId];
        return lease;
    }

    @AuraEnabled
    public static List<ContentDocument> getAllLeaseFilesById(String leaseId){
        try {
            List<ContentDocumentLink> CDLs = [SELECT ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId = :leaseId];
            List <Id> CDIdList = new List <Id> ();
            if (CDLs.size() < 1) {
                return new List<ContentDocument>(); 
            }
                
            else {
                for(ContentDocumentLink cdl : CDLs) {
                    CDIdList.add(cdl.ContentDocumentId);
                }
            }
            
            List<ContentDocument> entries = [SELECT Id, Title, ContentSize, CreatedDate, FileType FROM ContentDocument WHERE Id IN :CDIdList];
            // List<ContentDocument> entries = [SELECT Id, Title, FileType FROM ContentDocument WHERE ContentDocument.Id IN (SELECT ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId = :leaseId)];
            return entries;         
        
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static ContentDocument getContentDocumentById(String contentDocumentId){
        // ContentDocument cd = [SELECT Id, Title, ContentSize, CreatedDate, FileType FROM ContentDocument WHERE Id =:contentDocumentId LIMIT 1];
        List<ContentDocument> contentDocList = new List<ContentDocument>();
        contentDocList = [SELECT Id, Title, ContentSize, CreatedDate, FileType FROM ContentDocument WHERE Id =:contentDocumentId LIMIT 1];
        if(contentDocList.size()>1){
            return contentDocList[0];
        } else{
            return new ContentDocument();
        }
    }

}