force-app/main/default/objects/Lease__c/Lease__c.object-meta.xml
<CustomObject>
    <label>Lease</label>
    <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Lease Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lease__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leases</relationshipLabel>
    <relationshipName>Leases1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lease__c/fields/cLease_Document_Name__c.field-meta.xml
<CustomField>
    <fullName>cLease_Document_Name__c</fullName>
    <formula>TEXT(Lease_Document_Name__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lease Document Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lease__c/fields/Lease_Document_Name__c.field-meta.xml
<CustomField>
    <fullName>Lease_Document_Name__c</fullName>
    <label>Lease Document Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Combined Lease</fullName>
            </value>
            <value>
                <fullName>Highlighted Lease</fullName>
            </value>
            <value>
                <fullName>Lease Amendment 01</fullName>
            </value>
            <value>
                <fullName>Lease Amendment 02</fullName>
            </value>
            <value>
                <fullName>Lease Amendment 03</fullName>
            </value>
            <value>
                <fullName>Lease Amendment 04</fullName>
            </value>
            <value>
                <fullName>Lease Amendment 05</fullName>
            </value>
            <value>
                <fullName>Lease Amendment 06</fullName>
            </value>
            <value>
                <fullName>Lease Amendment 07</fullName>
            </value>
            <value>
                <fullName>Lease Amendment 08</fullName>
            </value>
            <value>
                <fullName>Lease Amendment 09</fullName>
            </value>
            <value>
                <fullName>Lease Amendment 10</fullName>
            </value>
            <value>
                <fullName>Master Lease</fullName>
            </value>
            <value>
                <fullName>Consent</fullName>
            </value>
            <value>
                <fullName>Lease Commencement Memo</fullName>
            </value>
            <value>
                <fullName>Lease Amendment 01 Commencement Memo</fullName>
            </value>
            <value>
                <fullName>Lease Amendment 02 Commencement Memo</fullName>
            </value>
            <value>
                <fullName>Lease Amendment 03 Commencement Memo</fullName>
            </value>
            <value>
                <fullName>Lease Amendment 04 Commencement Memo</fullName>
            </value>
            <value>
                <fullName>Lease Amendment 05 Commencement Memo</fullName>
            </value>
            <value>
                <fullName>Indemnification Agreement</fullName>
            </value>
            <value>
                <fullName>Coworking/Executive Suite Lease</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CreateLeaseController.cls
public with sharing class CreateLeaseController {
    @AuraEnabled
    public static Lease__c saveLease( Lease__c lease) {
  
        upsert lease;   
        return lease;
        
    }
    @AuraEnabled
    public static string getAccountNameFromId(Id accountId){
        
            String name = '';
            name = [SELECT Name FROM Account WHERE Id =: accountId].Name;
            return name;
        
    }
    @AuraEnabled
    public static Boolean attachFile( Lease__c lease, String docId) {
    
        try{
            
        
            system.debug('lease:: ' + lease);
			// String VersId = [SELECT contentDocumentId FROM contentVersion WHERE Id =:DocVer.id].contentDocumentId;
			ContentDocumentLink docLink = new ContentDocumentLink();
			doclink.ContentDocumentId = docId;
			doclink.linkedEntityId = lease.Id;
			doclink.sharetype = 'I';
			doclink.visibility = 'AllUsers';
			upsert doclink;

            // Lease__c lease = [SELECT Id, Lease_Document_Name__c FROM Lease__c WHERE Id =:leaseId];
            ContentDocument cd = [SELECT Title FROM ContentDocument WHERE Id =: docId];
            cd.Title = lease.Lease_Document_Name__c;
            update cd;
            return true;
            }
        catch(Exception e){
            return false;
        }
	
    }

    @AuraEnabled
    public static void deleteFileById(String documentId){
        
            // Lease__c lease = [SELECT Id, Lease_Document_Name__c FROM Lease__c WHERE Id =:leaseId];
            ContentDocument cd = [SELECT Id, Title FROM ContentDocument WHERE Id =: documentId];
            // cd.Title = lease.Lease_Document_Name__c;
            delete cd;
        
    }

    @AuraEnabled
    public static List<Lease__c> getLeasesListByAccountId(Id accountId){
        try {
            List<Lease__c> leasesList = [SELECT cLease_Document_Name__c, Lease_Date__c FROM Lease__c WHERE Account__c =: accountId];
            return leasesList;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static void deleteLeasesByNameFromAccount(Id accountId, String docName){
        try {
            List<Lease__c> leasesList = [SELECT cLease_Document_Name__c FROM Lease__c WHERE Account__c=:accountId AND cLease_Document_Name__c =: docName];
            delete leasesList;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static void deleteLeasesByDateAndNameFromAccount(Id accountId, String docName, Date leaseDate){
        try {
            List<Lease__c> leasesList = [SELECT cLease_Document_Name__c FROM Lease__c WHERE Account__c=:accountId AND cLease_Document_Name__c =: docName AND Lease_Date__c =:leaseDate];
            delete leasesList;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}