force-app/main/default/objects/Building_Directory__c/Building_Directory__c.object-meta.xml
<CustomObject>
    <label>Directory Photo</label>
    <nameField>
        <displayFormat>BD-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Directory Photos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Commission__c/Commission__c.object-meta.xml
<CustomObject>
    <label>Commission</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Commission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Commission__c/fields/File_Location_Formula__c.field-meta.xml
<CustomField>
    <fullName>File_Location_Formula__c</fullName>
    <label>File Location Formula</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Commission__c/fields/File_Name_Formula__c.field-meta.xml
<CustomField>
    <fullName>File_Name_Formula__c</fullName>
    <label>File Name Formula</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Commission__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TBD</fullName>
                <default>true</default>
                <label>TBD</label>
            </value>
            <value>
                <fullName>Check</fullName>
            </value>
            <value>
                <fullName>Wire</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TriggerCommissionAttachmentHelper.cls
public class TriggerCommissionAttachmentHelper {
    public static void addFileLinkToCommissions(List<ContentDocumentLink> links){
        String commissionIdToUpdate;
        String contentDocumentIdCommission;
        String directoryIdToUpdate;
        String contentDocumentIdDirectory;
        for(ContentDocumentLink cdl : links){
            if(String.valueof(cdl.LinkedEntityId).startsWith('a0H')){
                commissionIdToUpdate = cdl.LinkedEntityId;
                contentDocumentIdCommission = cdl.ContentDocumentId;
            }
            if(String.valueof(cdl.LinkedEntityId).startsWith('a0I')){
                directoryIdToUpdate = cdl.LinkedEntityId;
            	contentDocumentIdDirectory = cdl.ContentDocumentId;
            }
        }
        if(!String.isBlank(commissionIdToUpdate)){
            for(Commission__c com : [SELECT Id, Payment_Method__c FROM Commission__c WHERE Id=:commissionIdToUpdate LIMIT 1]){
                com.File_Location_Formula__c = '/lightning/r/ContentDocument/'+contentDocumentIdCommission+'/view';
                for(ContentDocument cd : [SELECT Title FROM ContentDocument WHERE Id=:contentDocumentIdCommission LIMIT 1]){
                    com.File_Name_Formula__c = cd.Title;
                }
    			update com;
            }
        }
        if(!String.isBlank(directoryIdToUpdate)){
            for(Building_Directory__c d : [SELECT Id FROM Building_Directory__c WHERE Id=:directoryIdToUpdate LIMIT 1]){
                d.File_Location_Formula__c = '/lightning/r/ContentDocument/'+contentDocumentIdDirectory+'/view';
                for(ContentDocument cd : [SELECT Title FROM ContentDocument WHERE Id=:contentDocumentIdDirectory LIMIT 1]){
                    d.File_Name_Formula__c = cd.Title;
                }
    			update d;
            }
        }
    }
}