force-app/main/default/objects/Account/fields/Active_or_Inactive__c.field-meta.xml
<CustomField>
    <fullName>Active_or_Inactive__c</fullName>
    <label>Tenant Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active Client</fullName>
            </value>
            <value>
                <fullName>Inactive Client</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Not Pursuing</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
                <isActive>false</isActive>
                <label>Active</label>
            </value>
            <value>
                <fullName>Client</fullName>
                <isActive>false</isActive>
                <label>Client</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
                <isActive>false</isActive>
                <label>Inactive</label>
            </value>
            <value>
                <fullName>N/A</fullName>
                <isActive>false</isActive>
                <label>N/A</label>
            </value>
            <value>
                <fullName>Nurture</fullName>
                <isActive>false</isActive>
                <label>Nurture</label>
            </value>
            <value>
                <fullName>Passed</fullName>
                <isActive>false</isActive>
                <label>Passed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <label>Building</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Building__c/Building__c.object-meta.xml
<CustomObject>
    <label>Building</label>
    <nameField>
        <label>Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/building_account__c/building_account__c.object-meta.xml
<CustomObject>
    <description>Related Account with Building</description>
    <label>Building-Tenant</label>
    <nameField>
        <label>Building-Account Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Building-Tenants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/building_account__c/fields/Building_Account__c.field-meta.xml
<CustomField>
    <fullName>Building_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Related Building - Account</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>building_accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/building_account__c/fields/Building_BA__c.field-meta.xml
<CustomField>
    <fullName>Building_BA__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Related Building - Accounts</description>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipName>building_accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Flyer_Account__c/Flyer_Account__c.object-meta.xml
<CustomObject>
    <label>Flyer-Account</label>
    <nameField>
        <label>Flyer-Suite Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flyer-Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Flyer_Account__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Flyers</relationshipLabel>
    <relationshipName>Flyer_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Flyer_Account__c/fields/Building_Flyer__c.field-meta.xml
<CustomField>
    <fullName>Building_Flyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Building Flyer</label>
    <referenceTo>Flyers__c</referenceTo>
    <relationshipLabel>Flyers</relationshipLabel>
    <relationshipName>Flyer_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Flyer_Suite__c/Flyer_Suite__c.object-meta.xml
<CustomObject>
    <label>Flyer-Suite</label>
    <nameField>
        <label>Flyer-Suite Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flyer-Suites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Flyer_Suite__c/fields/Building_Flyer__c.field-meta.xml
<CustomField>
    <fullName>Building_Flyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Building Flyer</label>
    <referenceTo>Flyers__c</referenceTo>
    <relationshipLabel>Flyer</relationshipLabel>
    <relationshipName>Flyer_Suites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Flyer_Suite__c/fields/Suites__c.field-meta.xml
<CustomField>
    <fullName>Suites__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Suites</label>
    <referenceTo>Suites__c</referenceTo>
    <relationshipLabel>Flyers</relationshipLabel>
    <relationshipName>Flyer_Suites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Flyers__c/Flyers__c.object-meta.xml
<CustomObject>
    <label>Building Flyer</label>
    <nameField>
        <displayFormat>F-{0000}</displayFormat>
        <label>Flyer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Flyers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Flyers__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Flyers</relationshipLabel>
    <relationshipName>Flyers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Flyers__c/fields/Active_or_Inactive__c.field-meta.xml
<CustomField>
    <fullName>Active_or_Inactive__c</fullName>
    <label>Active or Inactive</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Flyers__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipName>Flyers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Flyers__c/fields/File__c.field-meta.xml
<CustomField>
    <fullName>File__c</fullName>
    <formula>HYPERLINK(File_Location__c, File_Name__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>File Location</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Flyers__c/fields/File_Location__c.field-meta.xml
<CustomField>
    <fullName>File_Location__c</fullName>
    <inlineHelpText>Upload Flyer below, open the PDF in Salesforce by clicking on the link, click the Public Link button at the top of the page, click Create Link, Copy Link, and paste into this field</inlineHelpText>
    <label>File Location</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Flyers__c/fields/Flyer_Date__c.field-meta.xml
<CustomField>
    <fullName>Flyer_Date__c</fullName>
    <inlineHelpText>Input date you received flyer from source</inlineHelpText>
    <label>Flyer Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Flyers__c/fields/Flyer_Type__c.field-meta.xml
<CustomField>
    <fullName>Flyer_Type__c</fullName>
    <label>Flyer Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Sublease</fullName>
            </value>
            <value>
                <fullName>Coworking</fullName>
            </value>
            <value>
                <fullName>Sale</fullName>
            </value>
            <value>
                <fullName>Direct and Sale</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Suites__c/Suites__c.object-meta.xml
<CustomObject>
    <label>Suites</label>
    <nameField>
        <displayFormat>SU-{0000}</displayFormat>
        <label>Suite Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Suites</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Suites__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Suites</relationshipLabel>
    <relationshipName>Suites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Suites__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Suites</relationshipLabel>
    <relationshipName>Suites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FlyersListController.cls
public with sharing class FlyersListController {
    @AuraEnabled 
    public static List<Flyers__c> getAllFlyersByAccountId(String accountId){
        
            List<Flyer_Account__c> flyerList = [SELECT Account__c, Building_Flyer__c FROM Flyer_Account__c WHERE Account__c =:accountId];
            List<Id> flyersIds = new List<Id>();
            for(Flyer_Account__c flyer : flyerList) {
                flyersIds.add(flyer.Building_Flyer__c);
            }

            List<Flyers__c> flyersListToReturn = [SELECT Id, Name, 	Flyer_Date__c, 	Flyer_Type__c, 	Active_or_Inactive__c, 	File__c, File_Name__c, File_Location__c FROM Flyers__c WHERE Id IN:flyersIds];
            return flyersListToReturn;
        
    }

    @AuraEnabled 
    public static List<Flyers__c> getAllFlyersBySuiteId(String suiteId){
        
            List<Flyer_Suite__c> flyerList = [SELECT Suites__c, Building_Flyer__c FROM Flyer_Suite__c WHERE Suites__c =:suiteId];
            List<Id> flyersIds = new List<Id>();
            for(Flyer_Suite__c flyer : flyerList) {
                flyersIds.add(flyer.Building_Flyer__c);
            }

            List<Flyers__c> flyersListToReturn = [SELECT Id, Name, 	Flyer_Date__c, 	Flyer_Type__c, 	Active_or_Inactive__c, 	File__c, File_Name__c, File_Location__c FROM Flyers__c WHERE Id IN:flyersIds];
            return flyersListToReturn;
        
    }

    @AuraEnabled 
    public static List<Flyers__c> getAllFlyersByBuildingId(String buildingId){
        // List<Flyer_Suite__c> flyerList = [SELECT Suites__c, Building_Flyer__c FROM Flyers__c WHERE Suites__c =:buildingId];
        // List<Id> flyersIds = new List<Id>();
        // for(Flyer_Suite__c flyer : flyerList) {
        //     flyersIds.add(flyer.Building_Flyer__c);
        // }

        List<Flyers__c> flyersListToReturn = [SELECT Id, Name, 	Flyer_Date__c, 	Flyer_Type__c, 	Active_or_Inactive__c, 	File__c, File_Name__c, File_Location__c FROM Flyers__c WHERE 	Building__c =:buildingId];
        return flyersListToReturn;
    }

    @AuraEnabled
    public static string getAccountNameFromId(Id accountId){
        
            String name = '';
            name = [SELECT Name FROM Account WHERE Id =: accountId].Name;
            system.debug('account id: ' + accountId);
            system.debug('name:: '+ name);
            return name;
        
    }

    @AuraEnabled
    public static String getSObjectTypeFromId(Id recordId){
        try {
            String sobjectType = String.valueOf(recordId.getsobjecttype());
             return sobjectType;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    @AuraEnabled
    public static List<ContentDocumentLink> getAllRelatedFilesById(List<String> recordIds){
        try { 
            List<ContentDocumentLink> CDLs = [SELECT Id, ContentDocumentId, LinkedEntityId FROM ContentDocumentLink WHERE LinkedEntityId IN:recordIds];
            // List <Id> CDIdList = new List <Id> ();
            // if (CDLs.size() < 1) {
            //     return new List<ContentDocument>(); 
            // }
                
            // else {
            //     for(ContentDocumentLink cdl : CDLs) {
            //         CDIdList.add(cdl.ContentDocumentId);
            //     }
            // }
                return CDLs;
            
            // List<ContentDocument> entries = [SELECT Id, Title, ContentSize, CreatedDate, FileType FROM ContentDocument WHERE Id IN :CDIdList];
            // List<ContentDocument> entries = [SELECT Id, Title, FileType FROM ContentDocument WHERE ContentDocument.Id IN (SELECT ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId = :leaseId)];
            // return entries;         
        
        } catch (Exception e) {
            system.debug(e);
            throw new AuraHandledException(e.getMessage());
        }
    }

    public class ContentDocumentWithFileName {
        @AuraEnabled
        public string ContentDocumentId;
        @AuraEnabled
        public string RelatedRecordId;
    }

    @AuraEnabled
    public static string getBuildingNameById(String buildingId){
        try {
            Building__c bld = [SELECT Name FROM Building__c WHERE Id=:buildingId LIMIT 1];
            return bld.Name;
        } catch (Exception e) {
            system.debug(e);
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static Building__c getBuildingNameAndIdByAccountId(String accountId){
        try {
            building_account__c buildingAccount = [SELECT Building_Account__c, Building_BA__c FROM building_account__c WHERE Building_Account__c =: accountId LIMIT 1];
            String buildingId = buildingAccount.Building_BA__c;
            Building__c building = new Building__c();
            if(buildingId != '' || !String.isBlank(buildingId)){
                building = [SELECT Name, Id FROM Building__c WHERE Id=:buildingId LIMIT 1];
                return building;
            }
            return building;
        } catch (Exception e) {
            system.debug(e);
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static Building__c getBuildingNameAndIdBySuiteId(String suiteId){
        try {
            Suites__c buildingAccount = [SELECT Id, Building__c FROM Suites__c WHERE Id =: suiteId LIMIT 1];
            String buildingId = buildingAccount.Building__c;
            Building__c building = new Building__c();
            if(buildingId != '' || !String.isBlank(buildingId)){
                building = [SELECT Name, Id FROM Building__c WHERE Id=:buildingId LIMIT 1];
                return building;
            }
            return building;
        } catch (Exception e) {
            system.debug(e);
            throw new AuraHandledException(e.getMessage());
        }
    }
}