force-app/main/default/objects/Account/fields/Active_or_Inactive__c.field-meta.xml
<CustomField>
    <fullName>Active_or_Inactive__c</fullName>
    <label>Tenant Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active Client</fullName>
            </value>
            <value>
                <fullName>Inactive Client</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Not Pursuing</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
                <isActive>false</isActive>
                <label>Active</label>
            </value>
            <value>
                <fullName>Client</fullName>
                <isActive>false</isActive>
                <label>Client</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
                <isActive>false</isActive>
                <label>Inactive</label>
            </value>
            <value>
                <fullName>N/A</fullName>
                <isActive>false</isActive>
                <label>N/A</label>
            </value>
            <value>
                <fullName>Nurture</fullName>
                <isActive>false</isActive>
                <label>Nurture</label>
            </value>
            <value>
                <fullName>Passed</fullName>
                <isActive>false</isActive>
                <label>Passed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <label>Building</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Building__c/Building__c.object-meta.xml
<CustomObject>
    <label>Building</label>
    <nameField>
        <label>Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/building_account__c/building_account__c.object-meta.xml
<CustomObject>
    <description>Related Account with Building</description>
    <label>Building-Tenant</label>
    <nameField>
        <label>Building-Account Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Building-Tenants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/building_account__c/fields/Building_Account__c.field-meta.xml
<CustomField>
    <fullName>Building_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Related Building - Account</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>building_accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/building_account__c/fields/Building_BA__c.field-meta.xml
<CustomField>
    <fullName>Building_BA__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Related Building - Accounts</description>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipName>building_accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Flyer_Account__c/Flyer_Account__c.object-meta.xml
<CustomObject>
    <label>Flyer-Account</label>
    <nameField>
        <label>Flyer-Suite Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flyer-Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Flyer_Account__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Flyers</relationshipLabel>
    <relationshipName>Flyer_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Flyer_Account__c/fields/Building_Flyer__c.field-meta.xml
<CustomField>
    <fullName>Building_Flyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Building Flyer</label>
    <referenceTo>Flyers__c</referenceTo>
    <relationshipLabel>Flyers</relationshipLabel>
    <relationshipName>Flyer_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Flyer_Suite__c/Flyer_Suite__c.object-meta.xml
<CustomObject>
    <label>Flyer-Suite</label>
    <nameField>
        <label>Flyer-Suite Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flyer-Suites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Flyer_Suite__c/fields/Building_Flyer__c.field-meta.xml
<CustomField>
    <fullName>Building_Flyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Building Flyer</label>
    <referenceTo>Flyers__c</referenceTo>
    <relationshipLabel>Flyer</relationshipLabel>
    <relationshipName>Flyer_Suites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Flyer_Suite__c/fields/Suites__c.field-meta.xml
<CustomField>
    <fullName>Suites__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Suites</label>
    <referenceTo>Suites__c</referenceTo>
    <relationshipLabel>Flyers</relationshipLabel>
    <relationshipName>Flyer_Suites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Flyers__c/Flyers__c.object-meta.xml
<CustomObject>
    <label>Building Flyer</label>
    <nameField>
        <displayFormat>F-{0000}</displayFormat>
        <label>Flyer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Flyers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Flyers__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Flyers</relationshipLabel>
    <relationshipName>Flyers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Flyers__c/fields/Active_or_Inactive__c.field-meta.xml
<CustomField>
    <fullName>Active_or_Inactive__c</fullName>
    <label>Active or Inactive</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Flyers__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipName>Flyers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Flyers__c/fields/Flyer_Type__c.field-meta.xml
<CustomField>
    <fullName>Flyer_Type__c</fullName>
    <label>Flyer Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Sublease</fullName>
            </value>
            <value>
                <fullName>Coworking</fullName>
            </value>
            <value>
                <fullName>Sale</fullName>
            </value>
            <value>
                <fullName>Direct and Sale</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Suites__c/Suites__c.object-meta.xml
<CustomObject>
    <label>Suites</label>
    <nameField>
        <displayFormat>SU-{0000}</displayFormat>
        <label>Suite Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Suites</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Suites__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Suites</relationshipLabel>
    <relationshipName>Suites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Suites__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Suites</relationshipLabel>
    <relationshipName>Suites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FlyersListControllerTest.cls
@isTest
public with sharing class FlyersListControllerTest {
    @isTest
    public static void getAllFlyersByAccountIdTest() {
		Account ac = new Account(Name='123');
        insert ac;
        Flyers__c flyer = new Flyers__c(Account__c=ac.Id, Flyer_Type__c='Direct', Active_or_Inactive__c='Active');
        insert flyer;
        
        Flyer_Account__c flyerAccountJunction = new Flyer_Account__c(Account__c=ac.Id, Building_Flyer__c=flyer.Id);
        insert flyerAccountJunction;
        List<Flyers__c> flyersListToReturn = FlyersListController.getAllFlyersByAccountId(ac.Id);
        system.assertEquals(1, flyersListToReturn.size());
    }
    
    @isTest
    public static void getAllFlyersBySuiteIdTest(){
        Account ac = new Account(Name='123');
        insert ac;
        Flyers__c flyer = new Flyers__c(Account__c=ac.Id, Flyer_Type__c='Direct', Active_or_Inactive__c='Active');
        insert flyer;
        
        Building__c b= new Building__c(Name='test building');
        insert b;
        Suites__c suite = new Suites__c(Building__c=b.Id);
        insert suite;
        
        Flyer_Suite__c flyerSuiteJunction = new Flyer_Suite__c(Building_Flyer__c=flyer.Id, Suites__c=suite.Id);
        insert flyerSuiteJunction;
        List<Flyers__c> flyersListToReturn = FlyersListController.getAllFlyersBySuiteId(suite.Id);
        system.assertEquals(1, flyersListToReturn.size());
    }
    
    @isTest
    public static void getAllFlyersByBuildingIdTest(){
        Building__c b= new Building__c(Name='test building');
        insert b;
        Flyers__c flyer = new Flyers__c(Building__c=b.Id, Flyer_Type__c='Direct', Active_or_Inactive__c='Active');
        insert flyer;
        List<Flyers__c> flyersListToReturn = FlyersListController.getAllFlyersByBuildingId(b.Id);
        system.assertEquals(1, flyersListToReturn.size());
    }
    
    @isTest
    public static void getAccountNameFromIdTest(){
        Account ac = new Account(Name='test123');
        insert ac;
        String accountName = FlyersListController.getAccountNameFromId(ac.Id);
        system.assertEquals('test123', accountName);
    }
    
    @isTest
    public static void getSObjectTypeFromIdTest(){
        Account ac = new Account(Name='test123');
        insert ac;
        String objectType = FlyersListController.getSObjectTypeFromId(ac.Id);
        system.assertEquals('Account', objectType);
    }
    
    @isTest
    public static void getBuildingNameByIdTest(){
        Building__c b= new Building__c(Name='test building');
        insert b;
        String buildingName = FlyersListController.getBuildingNameById(b.Id);
        system.assertEquals('test building', buildingName);
    }
    
    @isTest
    public static void getAllRelatedFilesByIdTest(){
        Building__c b= new Building__c(Name='test building');
        insert b;
        List<String> idsList = new List<String>();
        idsList.add(b.Id);
        FlyersListController.getAllRelatedFilesById(idsList);
    }
    
    @isTest
    public static void getBuildingNameAndIdByAccountIdTest(){
        Account ac = new Account(Name='test123');
        insert ac;
        Building__c b= new Building__c(Name='test building');
        insert b;
        building_account__c buildingAccount = new building_account__c(Building_Account__c=ac.Id, Building_BA__c=b.Id);
        insert buildingAccount;
        
		FlyersListController.getBuildingNameAndIdByAccountId(ac.Id);   
    }
    
    @isTest
    public static void getBuildingNameAndIdBySuiteIdTest(){
        Building__c b= new Building__c(Name='test building');
        insert b;
        Suites__c suite = new Suites__c(Building__c=b.Id);
        insert suite;
        
		FlyersListController.getBuildingNameAndIdBySuiteId(suite.Id);   
    }
}