force-app/main/default/objects/Account/fields/Active_or_Inactive__c.field-meta.xml
<CustomField>
    <fullName>Active_or_Inactive__c</fullName>
    <label>Tenant Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active Client</fullName>
            </value>
            <value>
                <fullName>Inactive Client</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Not Pursuing</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
                <isActive>false</isActive>
                <label>Active</label>
            </value>
            <value>
                <fullName>Client</fullName>
                <isActive>false</isActive>
                <label>Client</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
                <isActive>false</isActive>
                <label>Inactive</label>
            </value>
            <value>
                <fullName>N/A</fullName>
                <isActive>false</isActive>
                <label>N/A</label>
            </value>
            <value>
                <fullName>Nurture</fullName>
                <isActive>false</isActive>
                <label>Nurture</label>
            </value>
            <value>
                <fullName>Passed</fullName>
                <isActive>false</isActive>
                <label>Passed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <label>Building</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>This is the city in which the building is located.</description>
    <label>City</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>This is the country in which the building is located.</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>USA</fullName>
                <default>true</default>
                <label>USA</label>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Mexico</fullName>
            </value>
            <value>
                <fullName>England</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Property_Address__c.field-meta.xml
<CustomField>
    <fullName>Property_Address__c</fullName>
    <description>This is the address of the property and shall not include the suite number, floors, city, state or zip.</description>
    <label>Property Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Pursuit_Status__c.field-meta.xml
<CustomField>
    <fullName>Pursuit_Status__c</fullName>
    <label>Pursuit Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Active_or_Inactive__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Research</fullName>
            </value>
            <value>
                <fullName>Intro Communication</fullName>
            </value>
            <value>
                <fullName>Direct Meeting</fullName>
            </value>
            <value>
                <fullName>Copy of Lease Received</fullName>
            </value>
            <value>
                <fullName>Evaluation/Abstract</fullName>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Suite_Floor__c.field-meta.xml
<CustomField>
    <fullName>Suite_Floor__c</fullName>
    <formula>if (isblank(text(Floor__c)),(Suite__c),( Suite__c &amp; &quot;/&quot; &amp; text( Floor__c )))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Suite/Floor</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <label>Client</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Prospect.recordType-meta.xml
<RecordType>
    <fullName>Prospect</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

force-app/main/default/objects/building_account__c/building_account__c.object-meta.xml
<CustomObject>
    <description>Related Account with Building</description>
    <label>Building-Tenant</label>
    <nameField>
        <label>Building-Account Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Building-Tenants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/building_account__c/fields/Building_Account__c.field-meta.xml
<CustomField>
    <fullName>Building_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Related Building - Account</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>building_accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/building_account__c/fields/Building_BA__c.field-meta.xml
<CustomField>
    <fullName>Building_BA__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Related Building - Accounts</description>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipName>building_accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>USA</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Mexico</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Property_Address__c.field-meta.xml
<CustomField>
    <fullName>Property_Address__c</fullName>
    <label>Property Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Suite_Floor__c.field-meta.xml
<CustomField>
    <fullName>Suite_Floor__c</fullName>
    <formula>if (isblank(text(Floor__c)),(Suite__c),( Suite__c &amp; &quot;/&quot; &amp; text( Floor__c )))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Suite/Floor</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Suites__c/Suites__c.object-meta.xml
<CustomObject>
    <label>Suites</label>
    <nameField>
        <displayFormat>SU-{0000}</displayFormat>
        <label>Suite Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Suites</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Suites__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Suites</relationshipLabel>
    <relationshipName>Suites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Suites__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Suites</relationshipLabel>
    <relationshipName>Suites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Suites__c/fields/Suite_Floor__c.field-meta.xml
<CustomField>
    <fullName>Suite_Floor__c</fullName>
    <label>Suite Floor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sub-Basement</fullName>
            </value>
            <value>
                <fullName>Basement</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>26</fullName>
            </value>
            <value>
                <fullName>27</fullName>
            </value>
            <value>
                <fullName>28</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Suites__c/fields/Suite_LEXP__c.field-meta.xml
<CustomField>
    <fullName>Suite_LEXP__c</fullName>
    <label>Suite LEXP</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Suites__c/fields/Suite_Number__c.field-meta.xml
<CustomField>
    <fullName>Suite_Number__c</fullName>
    <label>Suite Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Suites__c/fields/Vacant__c.field-meta.xml
<CustomField>
    <fullName>Vacant__c</fullName>
    <label>Vacant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Marketed for Sublease</fullName>
            </value>
            <value>
                <fullName>Marketed Direct</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Test_BuildingController.cls
@isTest
public class Test_BuildingController {
    
    static testMethod void getBuildingIdTest(){
        Lead l = new Lead();
        l.Property_Address__c = 'TestBilding';
        l.Company = 'newComanyTest';
        l.LastName = 'abc';
        insert l;

        //Get Account Record Type Id
        Id accountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Prospect').getRecordTypeId();
         
        //Create Account
        
        Account acc = new Account();
        acc.Property_Address__c = 'TestBilding';
        acc.Name = 'testAccount';
        acc.Active_or_Inactive__c = 'Prospect';
        acc.Pursuit_Status__c = 'Client';
        acc.RecordTypeId = accountRecordTypeId;
        insert acc;        
        
        Building__c build = new Building__c();
        build.Name = 'TestBilding';
        //build.Country__c = 'USA';
        build.Floors__c = 3;
        insert build;
        
        building_account__c buildAcc = new building_account__c();
        buildAcc.Building_Account__c = acc.Id;
        buildAcc.Building_BA__c = build.Id;
        insert buildAcc;
        
        
        Suites__c sui = new Suites__c();
        sui.Building__c = build.Id;
        sui.Account__c = acc.Id;
        sui.Suite_Floor__c = '1';
        sui.Suite_Number__c = '213';
        sui.Vacant__c= 'Yes';
        sui.Suite_LEXP__c = date.newInstance(2028,10,31);
        insert sui;
        
        BuildingController bc = new BuildingController(new ApexPages.StandardController(build));
    }
    
    @isTest
    public static void duplicateBuildingDataTest(){
        Building__c build = new Building__c();
        build.Name = 'TestBilding';
        build.City__c = 'San Francisco';
        //build.StatePK__c = 'CA';
        build.ZIP__c = '44000';
        insert build;
        
        
        Building__c build1 = new Building__c();
        build1.Name = 'TestBilding';
        build1.City__c = 'Los Angeles';
        //build.StatePK__c = 'CA';
        build1.ZIP__c = '44000';
        try{
            insert build1;    
        }
        catch(exception e){
            system.debug(e);
        }
        
        Building__c build2 = new Building__c();
        build2 = [SELECT Name, City__c, ZIP__c FROM Building__c WHERE City__c='San Francisco'][0];
        system.debug(build2);
        build2.City__c = 'Los Angeles';
        try{
            update build2;    
        }
        catch(exception e){
            System.debug(e);
        }
        
        Building__c build3 = new Building__c();
        build3.Name = 'TestBilding';
        build3.City__c = 'Los Angeles';
        //build.StatePK__c = 'CA';
        build3.ZIP__c = '44000';
        try{
            insert build3;    
        }
        catch(exception e){
            system.debug(e);
        }
        
        
    }

}