force-app/main/default/objects/Account/fields/Active_or_Inactive__c.field-meta.xml
<CustomField>
    <fullName>Active_or_Inactive__c</fullName>
    <label>Tenant Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active Client</fullName>
            </value>
            <value>
                <fullName>Inactive Client</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Not Pursuing</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
                <isActive>false</isActive>
                <label>Active</label>
            </value>
            <value>
                <fullName>Client</fullName>
                <isActive>false</isActive>
                <label>Client</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
                <isActive>false</isActive>
                <label>Inactive</label>
            </value>
            <value>
                <fullName>N/A</fullName>
                <isActive>false</isActive>
                <label>N/A</label>
            </value>
            <value>
                <fullName>Nurture</fullName>
                <isActive>false</isActive>
                <label>Nurture</label>
            </value>
            <value>
                <fullName>Passed</fullName>
                <isActive>false</isActive>
                <label>Passed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <label>Building</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Building__c/Building__c.object-meta.xml
<CustomObject>
    <label>Building</label>
    <nameField>
        <label>Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Flyer_Account__c/Flyer_Account__c.object-meta.xml
<CustomObject>
    <label>Flyer-Account</label>
    <nameField>
        <label>Flyer-Suite Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flyer-Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Flyer_Account__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Flyers</relationshipLabel>
    <relationshipName>Flyer_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Flyer_Account__c/fields/Building_Flyer__c.field-meta.xml
<CustomField>
    <fullName>Building_Flyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Building Flyer</label>
    <referenceTo>Flyers__c</referenceTo>
    <relationshipLabel>Flyers</relationshipLabel>
    <relationshipName>Flyer_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Flyer_Suite__c/Flyer_Suite__c.object-meta.xml
<CustomObject>
    <label>Flyer-Suite</label>
    <nameField>
        <label>Flyer-Suite Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flyer-Suites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Flyer_Suite__c/fields/Building_Flyer__c.field-meta.xml
<CustomField>
    <fullName>Building_Flyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Building Flyer</label>
    <referenceTo>Flyers__c</referenceTo>
    <relationshipLabel>Flyer</relationshipLabel>
    <relationshipName>Flyer_Suites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Flyer_Suite__c/fields/Suites__c.field-meta.xml
<CustomField>
    <fullName>Suites__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Suites</label>
    <referenceTo>Suites__c</referenceTo>
    <relationshipLabel>Flyers</relationshipLabel>
    <relationshipName>Flyer_Suites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Flyers__c/Flyers__c.object-meta.xml
<CustomObject>
    <label>Building Flyer</label>
    <nameField>
        <displayFormat>F-{0000}</displayFormat>
        <label>Flyer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Flyers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Flyers__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Flyers</relationshipLabel>
    <relationshipName>Flyers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Flyers__c/fields/Active_or_Inactive__c.field-meta.xml
<CustomField>
    <fullName>Active_or_Inactive__c</fullName>
    <label>Active or Inactive</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Flyers__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipName>Flyers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Flyers__c/fields/Flyer_Type__c.field-meta.xml
<CustomField>
    <fullName>Flyer_Type__c</fullName>
    <label>Flyer Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Sublease</fullName>
            </value>
            <value>
                <fullName>Coworking</fullName>
            </value>
            <value>
                <fullName>Sale</fullName>
            </value>
            <value>
                <fullName>Direct and Sale</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Suites__c/Suites__c.object-meta.xml
<CustomObject>
    <label>Suites</label>
    <nameField>
        <displayFormat>SU-{0000}</displayFormat>
        <label>Suite Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Suites</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Suites__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Suites</relationshipLabel>
    <relationshipName>Suites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Suites__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Suites</relationshipLabel>
    <relationshipName>Suites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FlyersRelatedListControllerTest.cls
@isTest
public with sharing class FlyersRelatedListControllerTest {
    @isTest
    public static void getFlyerRelatedAccountsByIdTest(){
        Account ac = new Account(Name='123');
        insert ac;
        Flyers__c flyer = new Flyers__c(Account__c=ac.Id, Flyer_Type__c='Direct', Active_or_Inactive__c='Active');
        insert flyer;
        
        Flyer_Account__c flyerAccountJunction = new Flyer_Account__c(Account__c=ac.Id, Building_Flyer__c=flyer.Id);
        insert flyerAccountJunction;
        
        List<Account> acList = FlyersRelatedListController.getFlyerRelatedAccountsById(flyer.Id);
        system.assertEquals(1, acList.size());
    }
    
    @isTest
    public static void getFlyerRelatedSuitesByIdTest(){
        Account ac = new Account(Name='123');
        insert ac;
        Flyers__c flyer = new Flyers__c(Account__c=ac.Id, Flyer_Type__c='Direct', Active_or_Inactive__c='Active');
        insert flyer;
        Building__c b= new Building__c(Name='test building');
        insert b;
        Suites__c suite = new Suites__c(Building__c=b.Id);
        insert suite;
        
        Flyer_Suite__c flyerSuiteJunction = new Flyer_Suite__c(Building_Flyer__c=flyer.Id, Suites__c=suite.Id);
        insert flyerSuiteJunction;
        
        List<Suites__c> acList = FlyersRelatedListController.getFlyerRelatedSuitesById(flyer.Id);
        system.assertEquals(1, acList.size());
    }
}