force-app/main/default/objects/Account/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <label>Building</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>This is the country in which the building is located.</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>USA</fullName>
                <default>true</default>
                <label>USA</label>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Mexico</fullName>
            </value>
            <value>
                <fullName>England</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Building__c/Building__c.object-meta.xml
<CustomObject>
    <label>Building</label>
    <nameField>
        <label>Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/building_account__c/building_account__c.object-meta.xml
<CustomObject>
    <description>Related Account with Building</description>
    <label>Building-Tenant</label>
    <nameField>
        <label>Building-Account Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Building-Tenants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/building_account__c/fields/Building_Account__c.field-meta.xml
<CustomField>
    <fullName>Building_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Related Building - Account</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>building_accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/building_account__c/fields/Building_BA__c.field-meta.xml
<CustomField>
    <fullName>Building_BA__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Related Building - Accounts</description>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipName>building_accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/building_lead__c/building_lead__c.object-meta.xml
<CustomObject>
    <description>Related Building with Leads</description>
    <label>Building-Tenant Old</label>
    <nameField>
        <label>Building-Tenant Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Building-Tenants Old</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/building_lead__c/fields/Building_BL__c.field-meta.xml
<CustomField>
    <fullName>Building_BL__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Related Building - Lead</description>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipName>building_leads</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/building_lead__c/fields/Building_Lead__c.field-meta.xml
<CustomField>
    <fullName>Building_Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Building</description>
    <label>Tenant</label>
    <referenceTo>Lead</referenceTo>
    <relationshipName>building_leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>USA</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Mexico</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/NewSuiteCreationTest.cls
@isTest
public class NewSuiteCreationTest {
    static testMethod void getBuildingIdTest(){
        Building__c build = new Building__c();
        build.Name = 'TestBilding';
        build.Country__c = 'USA';
        insert build;
        Account acc = new Account();
        acc.Name = 'testAccount';
        insert acc;
        building_account__c buildAcc = new building_account__c();
        buildAcc.Building_Account__c = acc.Id;
        buildAcc.Building_BA__c = build.Id;
        insert buildAcc;
        system.debug('build.Id'+build.Id + ' buildAcc: '+buildAcc.Id);
        NewSuiteCreation.getBuildingId(acc.Id);
        NewSuiteCreation.getBuildingId(null);
        Lead ld = new Lead();
        ld.Company = 'testCompany';
        ld.LastName = 'testContact';
        insert ld;
        building_lead__c builLead = new building_lead__c();
        builLead.Building_Lead__c = ld.Id;
        builLead.Building_BL__c = build.Id;
        insert builLead;
        NewSuiteCreation.getBuildingId(ld.Id);
        NewSuiteCreation.getBuildingId(build.Id);
    }
}