force-app/main/default/objects/Account/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <label>Building</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Full_Address__c.field-meta.xml
<CustomField>
    <fullName>Full_Address__c</fullName>
    <formula>LOWER( Property_Address__c) &amp; LOWER(City__c )&amp; LOWER(Text(State__c))</formula>
    <label>Full Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Building__c/Building__c.object-meta.xml
<CustomObject>
    <label>Building</label>
    <nameField>
        <label>Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Building__c/fields/Full_Address__c.field-meta.xml
<CustomField>
    <fullName>Full_Address__c</fullName>
    <formula>LOWER( Name)   &amp;  LOWER(City__c )&amp;  LOWER(text(StatePK__c))</formula>
    <inlineHelpText>This field will be automatically created based on the Address, City and State fields that are input above.</inlineHelpText>
    <label>Full Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/building_account__c/building_account__c.object-meta.xml
<CustomObject>
    <description>Related Account with Building</description>
    <label>Building-Tenant</label>
    <nameField>
        <label>Building-Account Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Building-Tenants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/building_account__c/fields/Building_Account__c.field-meta.xml
<CustomField>
    <fullName>Building_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Related Building - Account</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>building_accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/building_account__c/fields/Building_BA__c.field-meta.xml
<CustomField>
    <fullName>Building_BA__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Related Building - Accounts</description>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipName>building_accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AccountTriggerHelper.cls
public class AccountTriggerHelper {

    public static void InsertBuilding(list<Account> AccountList)
    {
        MAP<string,id> AccAddMap = new MAP<string,id>();
        List<Account> accList = new List<Account>();
        for(Account l : AccountList)
        {
            
            if ( string.isNotBlank(l.Full_Address__c))
            	AccAddMap.put(l.Full_Address__c.toLowerCase() ,l.id );
        }

        list<building_account__c> OAcclist = new list<building_account__c>();
        for(Building__c oBuild : [select id,Full_Address__c from Building__c where Full_Address__c = :AccAddMap.keyset() ])
        {
            if(AccAddMap.containsKey(oBuild.Full_Address__c))
            {
                building_account__c OLead = new building_account__c(Building_BA__c = oBuild.id , Building_Account__c = AccAddMap.get(oBuild.Full_Address__c));
                Account acc = new Account();
                acc.Id = AccAddMap.get(oBuild.Full_Address__c);
                acc.Building_Id__c = oBuild.id;
                accList.add(acc);
                OLead.name =string.valueof( oBuild.id  )+  string.valueof(AccAddMap.get(oBuild.Full_Address__c) );
                OAcclist.add(Olead);
            }
        }
        If(!OAcclist.isEmpty())
        {
            system.debug('hello test');
            upsert OAcclist name;
        }
        If(!accList.isEmpty())
        {
            StopUpdateRecursion.isfutureupdate=true;
            update accList;
        }
        
    }  
}