force-app/main/default/objects/Account/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <label>Building</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Building__c/Building__c.object-meta.xml
<CustomObject>
    <label>Building</label>
    <nameField>
        <label>Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/building_account__c/building_account__c.object-meta.xml
<CustomObject>
    <description>Related Account with Building</description>
    <label>Building-Tenant</label>
    <nameField>
        <label>Building-Account Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Building-Tenants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/building_account__c/fields/Building_Account__c.field-meta.xml
<CustomField>
    <fullName>Building_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Related Building - Account</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>building_accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/building_account__c/fields/Building_BA__c.field-meta.xml
<CustomField>
    <fullName>Building_BA__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Related Building - Accounts</description>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipName>building_accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Flyer_Account__c/Flyer_Account__c.object-meta.xml
<CustomObject>
    <label>Flyer-Account</label>
    <nameField>
        <label>Flyer-Suite Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flyer-Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Flyer_Account__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Flyers</relationshipLabel>
    <relationshipName>Flyer_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Flyer_Account__c/fields/Building_Flyer__c.field-meta.xml
<CustomField>
    <fullName>Building_Flyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Building Flyer</label>
    <referenceTo>Flyers__c</referenceTo>
    <relationshipLabel>Flyers</relationshipLabel>
    <relationshipName>Flyer_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Flyer_Suite__c/Flyer_Suite__c.object-meta.xml
<CustomObject>
    <label>Flyer-Suite</label>
    <nameField>
        <label>Flyer-Suite Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flyer-Suites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Flyer_Suite__c/fields/Building_Flyer__c.field-meta.xml
<CustomField>
    <fullName>Building_Flyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Building Flyer</label>
    <referenceTo>Flyers__c</referenceTo>
    <relationshipLabel>Flyer</relationshipLabel>
    <relationshipName>Flyer_Suites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Flyer_Suite__c/fields/Suites__c.field-meta.xml
<CustomField>
    <fullName>Suites__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Suites</label>
    <referenceTo>Suites__c</referenceTo>
    <relationshipLabel>Flyers</relationshipLabel>
    <relationshipName>Flyer_Suites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Flyers__c/Flyers__c.object-meta.xml
<CustomObject>
    <label>Building Flyer</label>
    <nameField>
        <displayFormat>F-{0000}</displayFormat>
        <label>Flyer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Flyers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Flyers__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Flyers</relationshipLabel>
    <relationshipName>Flyers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Flyers__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipName>Flyers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Flyers__c/fields/File_Location__c.field-meta.xml
<CustomField>
    <fullName>File_Location__c</fullName>
    <inlineHelpText>Upload Flyer below, open the PDF in Salesforce by clicking on the link, click the Public Link button at the top of the page, click Create Link, Copy Link, and paste into this field</inlineHelpText>
    <label>File Location</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Lease__c/Lease__c.object-meta.xml
<CustomObject>
    <label>Lease</label>
    <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Lease Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lease__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leases</relationshipLabel>
    <relationshipName>Leases1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lease__c/fields/Lease_Document_Name__c.field-meta.xml
<CustomField>
    <fullName>Lease_Document_Name__c</fullName>
    <label>Lease Document Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Combined Lease</fullName>
            </value>
            <value>
                <fullName>Highlighted Lease</fullName>
            </value>
            <value>
                <fullName>Lease Amendment 01</fullName>
            </value>
            <value>
                <fullName>Lease Amendment 02</fullName>
            </value>
            <value>
                <fullName>Lease Amendment 03</fullName>
            </value>
            <value>
                <fullName>Lease Amendment 04</fullName>
            </value>
            <value>
                <fullName>Lease Amendment 05</fullName>
            </value>
            <value>
                <fullName>Lease Amendment 06</fullName>
            </value>
            <value>
                <fullName>Lease Amendment 07</fullName>
            </value>
            <value>
                <fullName>Lease Amendment 08</fullName>
            </value>
            <value>
                <fullName>Lease Amendment 09</fullName>
            </value>
            <value>
                <fullName>Lease Amendment 10</fullName>
            </value>
            <value>
                <fullName>Master Lease</fullName>
            </value>
            <value>
                <fullName>Consent</fullName>
            </value>
            <value>
                <fullName>Lease Commencement Memo</fullName>
            </value>
            <value>
                <fullName>Lease Amendment 01 Commencement Memo</fullName>
            </value>
            <value>
                <fullName>Lease Amendment 02 Commencement Memo</fullName>
            </value>
            <value>
                <fullName>Lease Amendment 03 Commencement Memo</fullName>
            </value>
            <value>
                <fullName>Lease Amendment 04 Commencement Memo</fullName>
            </value>
            <value>
                <fullName>Lease Amendment 05 Commencement Memo</fullName>
            </value>
            <value>
                <fullName>Indemnification Agreement</fullName>
            </value>
            <value>
                <fullName>Coworking/Executive Suite Lease</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Suites__c/Suites__c.object-meta.xml
<CustomObject>
    <label>Suites</label>
    <nameField>
        <displayFormat>SU-{0000}</displayFormat>
        <label>Suite Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Suites</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Suites__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Suites</relationshipLabel>
    <relationshipName>Suites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Suites__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Suites</relationshipLabel>
    <relationshipName>Suites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/NewFlyerController.cls
public with sharing class NewFlyerController {

    @AuraEnabled
    public static string getBuildingNameFromId(Id buildingId){
        try {
            Building__c building = [SELECT Name FROM Building__c WHERE Id=:buildingId LIMIT 1];
            String buildingName = building.Name;
            return buildingName;
        } catch (Exception e) {
            system.debug(e);
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static ContentDocument getContentDocumentById(String contentDocumentId){
        // ContentDocument cd = [SELECT Id, Title, ContentSize, CreatedDate, FileType FROM ContentDocument WHERE Id =:contentDocumentId LIMIT 1];
        List<ContentDocument> contentDocList = new List<ContentDocument>();
        contentDocList = [SELECT Id, Title, ContentSize, CreatedDate, FileType FROM ContentDocument WHERE Id =:contentDocumentId LIMIT 1];
        if(contentDocList.size()>1){
            return contentDocList[0];
        } else{
            return new ContentDocument();
        }
    }
    @AuraEnabled
    public static Flyers__c saveFlyer( Flyers__c flyer) {
        upsert flyer;   
        return flyer;   
    }
    @AuraEnabled
    public static Boolean attachFile( Flyers__c flyer, String docId) {
        try{
            String fileName = '';
            List<ContentDocument> CDList = [SELECT Title FROM ContentDocument WHERE Id =: docId LIMIT 1];
            if(CDList.size()>0){
                fileName = CDList[0].Title;
            }
            flyer.File_Location__c = '/lightning/r/ContentDocument/'+docId+'/view';
            flyer.File_Name__c = fileName;
            update flyer;
			// String VersId = [SELECT contentDocumentId FROM contentVersion WHERE Id =:DocVer.id].contentDocumentId;
			ContentDocumentLink docLink = new ContentDocumentLink();
			doclink.ContentDocumentId = docId;
			doclink.linkedEntityId = flyer.Id;
			doclink.sharetype = 'I';
			doclink.visibility = 'AllUsers';
			upsert doclink;

            // Lease__c lease = [SELECT Id, Lease_Document_Name__c FROM Lease__c WHERE Id =:leaseId];
            ContentDocument cd = [SELECT Title FROM ContentDocument WHERE Id =: docId];
            cd.Title = flyer.Name;
            update cd;
            return true;
        }
        catch(Exception e){
            return false;
        }
	
    }

    @AuraEnabled
    public static List<String> getBuildingAccountIds(String buildingId){
        try {
            List<building_account__c> buildingAccounts = [SELECT Building_Account__c, Building_BA__c FROM building_account__c WHERE Building_BA__c =: buildingId];
            List<String> buildingAccountIds = new List<String> ();
            for(building_account__c BA : buildingAccounts){
                buildingAccountIds.add(BA.Building_Account__c);
            }
            system.debug('building Accounts' + buildingAccountIds);
            return buildingAccountIds;
        } catch (Exception e) {
            system.debug(e);
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static void addFlyerRelationshipWithAccounts(Id flyerId, List<Id> accountIds){
        try {
            // List<Account> accountList = [SELECT Id FROM Account WHERE Id IN:accountIds];
            // for(Account ac : accountList){
            //     ac.Building_Flyer__c = flyerId;
            // }
            // update accountList;
            List<Flyer_Account__c> flyersList = new List<Flyer_Account__c>();
            for(Id accountId : accountIds){
                Flyer_Account__c flyerAccount = new Flyer_Account__c();
                flyerAccount.Building_Flyer__c = flyerId;
                flyerAccount.Account__c = accountId;
                flyersList.add(flyerAccount);
            }
            insert flyersList;
            // Flyer_Account__c 
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    @AuraEnabled
    public static void addFlyerRelationshipWithSuites(Id flyerId, List<Id> suiteIds){
        try {
            // List<Suites__c> suiteList = [SELECT Id FROM Suites__c WHERE Id IN:suitesIds];
            // for(Suites__c suite : suiteList){
            //     suite.Building_Flyer__c = flyerId;
            // }
            // update suiteList;
            system.debug('suites IDds : ' + suiteIds);
            system.debug('flyer id : ' + flyerId);
            List<Flyer_Suite__c> flyersList = new List<Flyer_Suite__c>();
            for(Id suiteId : suiteIds){
                Flyer_Suite__c flyerSuite = new Flyer_Suite__c();
                flyerSuite.Building_Flyer__c = flyerId;
                flyerSuite.Suites__c = suiteId;
                flyersList.add(flyerSuite);
            }
            insert flyersList;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static String getBuildingIdByFlyerId(String flyerId){
        try {
            Flyers__c flyer = [SELECT Building__c FROM Flyers__c WHERE Id =:flyerId LIMIT 1];
            return flyer.Building__c;
        } catch (Exception e) {
            system.debug('Error: ' + e);
            throw new AuraHandledException(e.getMessage());
        }
    }
}