force-app/main/default/objects/Account/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <label>Building</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Building__c/Building__c.object-meta.xml
<CustomObject>
    <label>Building</label>
    <nameField>
        <label>Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/building_account__c/building_account__c.object-meta.xml
<CustomObject>
    <description>Related Account with Building</description>
    <label>Building-Tenant</label>
    <nameField>
        <label>Building-Account Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Building-Tenants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/building_account__c/fields/Building_Account__c.field-meta.xml
<CustomField>
    <fullName>Building_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Related Building - Account</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>building_accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/building_account__c/fields/Building_BA__c.field-meta.xml
<CustomField>
    <fullName>Building_BA__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Related Building - Accounts</description>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipName>building_accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/building_lead__c/building_lead__c.object-meta.xml
<CustomObject>
    <description>Related Building with Leads</description>
    <label>Building-Tenant Old</label>
    <nameField>
        <label>Building-Tenant Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Building-Tenants Old</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/building_lead__c/fields/Building_BL__c.field-meta.xml
<CustomField>
    <fullName>Building_BL__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Related Building - Lead</description>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipName>building_leads</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/building_lead__c/fields/Building_Lead__c.field-meta.xml
<CustomField>
    <fullName>Building_Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Building</description>
    <label>Tenant</label>
    <referenceTo>Lead</referenceTo>
    <relationshipName>building_leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Suites__c/Suites__c.object-meta.xml
<CustomObject>
    <label>Suites</label>
    <nameField>
        <displayFormat>SU-{0000}</displayFormat>
        <label>Suite Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Suites</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Suites__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Suites</relationshipLabel>
    <relationshipName>Suites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/NewSuiteCreation.cls
public class NewSuiteCreation {
    
    public static Map<Id, String> recordtypemap {get;set;}
    @AuraEnabled
    public static SuiteWrapper getBuildingId(String recordId) {
        if(recordId == null)
            return null;
        SuiteWrapper suWrap = new SuiteWrapper();
        String buildingId = '';
        String sObjName = Id.valueOf(recordId).getSObjectType().getDescribe().getName();
        if(sObjName == 'Account'){
            list<building_account__c> lstBuildingAccount = [select Id, Building_BA__c from building_account__c where Building_Account__c =: recordId];
            system.debug('lstBuildingAccount ' + lstBuildingAccount);
            if(lstBuildingAccount.size() > 0){
                //buildingId = lstBuildingAccount[0].Building_BA__c;
                suWrap.buildingId = lstBuildingAccount[0].Building_BA__c;
            }
        }
        if(sObjName == 'Lead'){
            list<building_lead__c> lstBuildingTenant = [select Id, Building_BL__c,Building_Lead__r.Company, Building_Lead__c from building_lead__c where Building_Lead__c =: recordId];
            if(lstBuildingTenant.size() > 0){
                //buildingId = lstBuildingTenant[0].Building_BL__c;
                suWrap.buildingId = lstBuildingTenant[0].Building_BL__c;
                suWrap.leadCompanyName = lstBuildingTenant[0].Building_Lead__r.Company;
                suWrap.leadId = lstBuildingTenant[0].Building_Lead__c;
            }
        }
        if(sObjName == 'Building__c'){
            list<Building__c> lstBuilding = [select Id from Building__c where Id =: recordId];
            if(lstBuilding.size() > 0){
                //buildingId = lstBuildingTenant[0].Building_BL__c;
                suWrap.buildingId = lstBuilding[0].Id;
            }
        }
        //if(buildingId != null && buildingId != '')
            return suWrap;
        /*else
            return null;*/
    }
    
    
      @AuraEnabled        
    public static List<String> fetchRecordTypeValues(){
        List<Schema.RecordTypeInfo> recordtypes = Suites__c.SObjectType.getDescribe().getRecordTypeInfos();    
        recordtypemap = new Map<Id, String>();
        for(RecordTypeInfo rt : recordtypes){
            if(rt.getName() != 'Master')
            recordtypemap.put(rt.getRecordTypeId(), rt.getName());
        }        
        return recordtypemap.values();
    }
    
    @AuraEnabled
    public static Id getRecTypeId(String recordTypeLabel){
        Id recid = Schema.SObjectType.Suites__c.getRecordTypeInfosByName().get(recordTypeLabel).getRecordTypeId();        
        return recid;
    }      
    public class SuiteWrapper{
        @AuraEnabled
        public String buildingId{get;set;}
        @AuraEnabled
        public String leadCompanyName{get;set;}
        @AuraEnabled
        public String leadId{get;set;}
    }
}