force-app/main/default/objects/Account/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <label>Building</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>This is the city in which the building is located.</description>
    <label>City</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Full_Address__c.field-meta.xml
<CustomField>
    <fullName>Full_Address__c</fullName>
    <formula>LOWER( Property_Address__c) &amp; LOWER(City__c )&amp; LOWER(Text(State__c))</formula>
    <label>Full Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <description>This is the zip code of the building.</description>
    <label>Zip</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Building__c/Building__c.object-meta.xml
<CustomObject>
    <label>Building</label>
    <nameField>
        <label>Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Building__c/fields/Full_Address__c.field-meta.xml
<CustomField>
    <fullName>Full_Address__c</fullName>
    <formula>LOWER( Name)   &amp;  LOWER(City__c )&amp;  LOWER(text(StatePK__c))</formula>
    <inlineHelpText>This field will be automatically created based on the Address, City and State fields that are input above.</inlineHelpText>
    <label>Full Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Building__c/fields/StatePK__c.field-meta.xml
<CustomField>
    <fullName>StatePK__c</fullName>
    <description>State Picklist</description>
    <label>State/Territory</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Country__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AB</fullName>
            </value>
            <value>
                <fullName>AG</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AreaC1</fullName>
            </value>
            <value>
                <fullName>AreaC2</fullName>
            </value>
            <value>
                <fullName>AreaC3</fullName>
            </value>
            <value>
                <fullName>AreaM1</fullName>
            </value>
            <value>
                <fullName>AreaM2</fullName>
            </value>
            <value>
                <fullName>AreaM3</fullName>
            </value>
            <value>
                <fullName>AreaUK1</fullName>
            </value>
            <value>
                <fullName>AreaUK2</fullName>
            </value>
            <value>
                <fullName>AreaUK3</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>BC</fullName>
            </value>
            <value>
                <fullName>BN</fullName>
            </value>
            <value>
                <fullName>BS</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CH</fullName>
            </value>
            <value>
                <fullName>CI</fullName>
            </value>
            <value>
                <fullName>CL</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CP</fullName>
            </value>
            <value>
                <fullName>CS</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>DF</fullName>
            </value>
            <value>
                <fullName>DG</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Building__c/fields/ZIP__c.field-meta.xml
<CustomField>
    <fullName>ZIP__c</fullName>
    <label>ZIP</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/building_account__c/building_account__c.object-meta.xml
<CustomObject>
    <description>Related Account with Building</description>
    <label>Building-Tenant</label>
    <nameField>
        <label>Building-Account Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Building-Tenants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/building_account__c/fields/Building_Account__c.field-meta.xml
<CustomField>
    <fullName>Building_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Related Building - Account</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>building_accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/building_account__c/fields/Building_BA__c.field-meta.xml
<CustomField>
    <fullName>Building_BA__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Related Building - Accounts</description>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipName>building_accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/building_lead__c/building_lead__c.object-meta.xml
<CustomObject>
    <description>Related Building with Leads</description>
    <label>Building-Tenant Old</label>
    <nameField>
        <label>Building-Tenant Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Building-Tenants Old</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/building_lead__c/fields/Building_BL__c.field-meta.xml
<CustomField>
    <fullName>Building_BL__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Related Building - Lead</description>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipName>building_leads</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/building_lead__c/fields/Building_Lead__c.field-meta.xml
<CustomField>
    <fullName>Building_Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Building</description>
    <label>Tenant</label>
    <referenceTo>Lead</referenceTo>
    <relationshipName>building_leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Full_Address__c.field-meta.xml
<CustomField>
    <fullName>Full_Address__c</fullName>
    <formula>LOWER( Property_Address__c) &amp; LOWER(City__c)&amp; LOWER(Text(State__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Full Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <label>Zip</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/BuildingTriggerHelper.cls
public class BuildingTriggerHelper {
    
    public static void InsertBuilding(list<Building__c> BuildingList)
    {
        MAP<string,id> AccAddMap = new MAP<string,id>();
        for(Building__c l : BuildingList)
        {
            AccAddMap.put(l.Full_Address__c.toLowerCase() ,l.id );
        }
        
        list<building_account__c> OAcclist = new list<building_account__c>();
        
        for(Account Oacc : [select id,Full_Address__c from Account where Full_Address__c = :AccAddMap.keyset() ])
        {
            if(AccAddMap.containsKey(Oacc.Full_Address__c))
            {
                building_account__c OLead = new building_account__c(Building_BA__c = AccAddMap.get(Oacc.Full_Address__c) , Building_Account__c = Oacc.id );
                OLead.name = string.valueof(AccAddMap.get(Oacc.Full_Address__c) )+ string.valueof(Oacc.id );
                OAcclist.add(Olead);
            }
        }
        list<building_lead__c> OLeadlist = new list<building_lead__c>();
        
        for(lead oLead : [select id,Full_Address__c from lead where Full_Address__c = :AccAddMap.keyset() ])
        {
            if(AccAddMap.containsKey(oLead.Full_Address__c))
            {
                building_lead__c OBl = new building_lead__c(Building_BL__c = AccAddMap.get(oLead.Full_Address__c)  , Building_Lead__c = oLead.id);
                OBl.name = string.valueof(AccAddMap.get(oLead.Full_Address__c) ) + string.valueof(oLead.id);
                system.debug('lead' +  OBl.name);
                OLeadlist.add(OBl);
            }
        }
        System.debug('OAcclist'+OAcclist);
        If(!OAcclist.isEmpty())
        {
            upsert OAcclist name;
        }
        If(!OLeadlist.isEmpty())
        {
            upsert OLeadlist name;
        }
        
    }  
    
    public static void checkDuplicateBefore(List<Building__c> newBldList, Map<Id,Building__c> oldBldMap){
        Set<String> buildingAddress = new Set<String>();
        List<Building__c> oldBldList = [SELECT Name, City__c, StatePK__c, ZIP__c FROM Building__c];
        for(Building__c bld: oldBldList){
            buildingAddress.add(bld.Name+bld.City__c+bld.StatePK__c+bld.ZIP__c);
        }
        String addressCheck = '';
        if(oldBldMap == null){
            for(Building__c b: newBldList){
                addressCheck = b.Name + b.City__c + b.StatePK__c + b.ZIP__c;
                if(buildingAddress.contains(addressCheck))
                {
                    b.addError('Building Already Exists');
                }
            }
        }
        else{
            for(Building__c b : newBldList){
                if(oldBldMap.get(b.id).Name != b.Name || oldBldMap.get(b.id).City__c != b.City__c || oldBldMap.get(b.id).ZIP__c != b.ZIP__c || oldBldMap.get(b.id).StatePK__c != b.StatePK__c){
                    addressCheck = b.Name + b.City__c + b.StatePK__c + b.ZIP__c;
                    if(buildingAddress.contains(addressCheck))
                    {
                        b.addError('Building Already Exists');
                    }
                }
            }    
        }
    }
}