force-app/main/default/objects/Account/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <label>Building</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>This is the city in which the building is located.</description>
    <label>City</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Full_Address__c.field-meta.xml
<CustomField>
    <fullName>Full_Address__c</fullName>
    <formula>LOWER( Property_Address__c) &amp; LOWER(City__c )&amp; LOWER(Text(State__c))</formula>
    <label>Full Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Building__c/Building__c.object-meta.xml
<CustomObject>
    <label>Building</label>
    <nameField>
        <label>Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Building__c/fields/Full_Address__c.field-meta.xml
<CustomField>
    <fullName>Full_Address__c</fullName>
    <formula>LOWER( Name)   &amp;  LOWER(City__c )&amp;  LOWER(text(StatePK__c))</formula>
    <inlineHelpText>This field will be automatically created based on the Address, City and State fields that are input above.</inlineHelpText>
    <label>Full Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Building__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>This is the name of the building, such as US Bank Tower.</description>
    <inlineHelpText>If Building is named within a campus, format &quot;&lt;Campus Name&gt;, &lt;Building Name&gt;&quot;</inlineHelpText>
    <label>Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Building__c/fields/StatePK__c.field-meta.xml
<CustomField>
    <fullName>StatePK__c</fullName>
    <description>State Picklist</description>
    <label>State/Territory</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Country__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AB</fullName>
            </value>
            <value>
                <fullName>AG</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AreaC1</fullName>
            </value>
            <value>
                <fullName>AreaC2</fullName>
            </value>
            <value>
                <fullName>AreaC3</fullName>
            </value>
            <value>
                <fullName>AreaM1</fullName>
            </value>
            <value>
                <fullName>AreaM2</fullName>
            </value>
            <value>
                <fullName>AreaM3</fullName>
            </value>
            <value>
                <fullName>AreaUK1</fullName>
            </value>
            <value>
                <fullName>AreaUK2</fullName>
            </value>
            <value>
                <fullName>AreaUK3</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>BC</fullName>
            </value>
            <value>
                <fullName>BN</fullName>
            </value>
            <value>
                <fullName>BS</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CH</fullName>
            </value>
            <value>
                <fullName>CI</fullName>
            </value>
            <value>
                <fullName>CL</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CP</fullName>
            </value>
            <value>
                <fullName>CS</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>DF</fullName>
            </value>
            <value>
                <fullName>DG</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Full_Address__c.field-meta.xml
<CustomField>
    <fullName>Full_Address__c</fullName>
    <formula>LOWER( Property_Address__c) &amp; LOWER(City__c)&amp; LOWER(Text(State__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Full Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Suites__c/Suites__c.object-meta.xml
<CustomObject>
    <label>Suites</label>
    <nameField>
        <displayFormat>SU-{0000}</displayFormat>
        <label>Suite Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Suites</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Suites__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Suites</relationshipLabel>
    <relationshipName>Suites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Suites__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Suites</relationshipLabel>
    <relationshipName>Suites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Suites__c/fields/Full_Address__c.field-meta.xml
<CustomField>
    <fullName>Full_Address__c</fullName>
    <formula>Building__r.Full_Address__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Full Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Suites__c/fields/Landlord_Use__c.field-meta.xml
<CustomField>
    <fullName>Landlord_Use__c</fullName>
    <label>Landlord Use</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Office of the Building</fullName>
            </value>
            <value>
                <fullName>Property Management</fullName>
            </value>
            <value>
                <fullName>None</fullName>
                <isActive>false</isActive>
                <label>None</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Suites__c/fields/Suite_Floor_Number__c.field-meta.xml
<CustomField>
    <fullName>Suite_Floor_Number__c</fullName>
    <formula>VALUE(TEXT(Suite_Floor__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Suite Floor Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Suites__c/fields/Suite_LEXP__c.field-meta.xml
<CustomField>
    <fullName>Suite_LEXP__c</fullName>
    <label>Suite LEXP</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Suites__c/fields/Suite_Number__c.field-meta.xml
<CustomField>
    <fullName>Suite_Number__c</fullName>
    <label>Suite Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Suites__c/fields/Suite_RSF__c.field-meta.xml
<CustomField>
    <fullName>Suite_RSF__c</fullName>
    <label>Suite RSF</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Suites__c/fields/Tenant__c.field-meta.xml
<CustomField>
    <fullName>Tenant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tenant</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Suites</relationshipLabel>
    <relationshipName>Suites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Suites__c/fields/Vacant__c.field-meta.xml
<CustomField>
    <fullName>Vacant__c</fullName>
    <label>Vacant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Marketed for Sublease</fullName>
            </value>
            <value>
                <fullName>Marketed Direct</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Suites__c/recordTypes/Vacancy.recordType-meta.xml
<RecordType>
    <fullName>Vacancy</fullName>
    <active>true</active>
    <label>Vacancy</label>
</RecordType>

force-app/main/default/objects/Year_Color__mdt/Year_Color__mdt.object-meta.xml
<CustomObject>
    <label>Year Color</label>
    <pluralLabel>Year Colors</pluralLabel>
</CustomObject>

force-app/main/default/objects/Year_Color__mdt/fields/Color__c.field-meta.xml
<CustomField>
    <fullName>Color__c</fullName>
    <label>Color</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Year_Color__mdt/fields/textColor__c.field-meta.xml
<CustomField>
    <fullName>textColor__c</fullName>
    <label>textColor</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Year_Color__mdt/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2023</fullName>
                <default>true</default>
                <label>2023</label>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
            <value>
                <fullName>2028</fullName>
            </value>
            <value>
                <fullName>2029</fullName>
            </value>
            <value>
                <fullName>2030</fullName>
            </value>
            <value>
                <fullName>2031</fullName>
            </value>
            <value>
                <fullName>2032</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BuildingController.cls
public class BuildingController {
   
    public BuildingResponse resp{get;set;}
    
    public Map<String,Year_Color__mdt> getYearColor(){
        Map<String,Year_Color__mdt> ycmap = new Map<String,Year_Color__mdt>();
        for(Year_Color__mdt yc : [select id,color__c, year__c,textColor__c from Year_Color__mdt]){
            ycmap.put(yc.year__c, yc);
        }
        return ycmap;
    }
    
    public BuildingController(Apexpages.StandardController std){
        Map<String,Year_Color__mdt> ycmap = getYearColor();
        resp = new BuildingResponse();
        List<Building__c> buildingList = [Select Id,Name__c,Name,Full_Address__c,Floors__c,City__c,StatePK__c from Building__c
                                          where Id=: std.getId()];
        
        if(buildingList.size() > 0){
            List<Suites__c> suitesList = [Select Id,RecordTypeId, Name,Suite_Floor_Number__c,Suite_Number__c,Suite_RSF__c,Suite_LEXP__c,Account__c,Building__c,
                                          Account__r.Name, Tenant__c, Tenant__r.Company, Vacant__c,Landlord_Use__c,Not_Tracked__c from Suites__c 
                                          where Building__c =: buildingList[0].Id
                                          order by Suite_Floor_Number__c desc];
            
            
            Map<Decimal,List<Suites__c>> suitesMap = new Map<Decimal,List<Suites__c>>();
            for(Suites__c s: suitesList){
                if(!suitesMap.containsKey(s.Suite_Floor_Number__c)){
                    suitesMap.put(s.Suite_Floor_Number__c, new List<Suites__c>{s});
                }
                else{
                    List<Suites__c> existing = suitesMap.get(s.Suite_Floor_Number__c);
                    existing.add(s);
                    suitesMap.put(s.Suite_Floor_Number__c, existing);
                }
            }
     
            
            Building__c c= buildingList[0];
            system.debug('Building' + c);
            resp.Name = c.Name__c;
            resp.Address = c.Name + ', ' + c.City__c + ', ' + c.StatePK__c;
            resp.suiteInfoList = new List<SuiteInfo>();
            SuiteInfo si;
            for(Decimal i=c.Floors__c; i > 0; i--){
                
                si = new SuiteInfo();
                si.FloorNumber = String.valueOf(i);
                if(suitesMap.containsKey(i)){
                    List<Suites__c> floorSuites = suitesMap.get(i);
                    si.individualSuiteList = new List<IndividualSuite>();
                    
                    for(Suites__c fs : floorSuites){
                        
                        IndividualSuite isrec = new IndividualSuite();
                        isrec.Name = '';
                        if(fs.Account__r.Name != null){
                            isrec.Name = fs.Account__r.Name + ' ';
                            isrec.Link = URL.getOrgDomainUrl().toExternalForm() +'/' + fs.Account__c;
                        }
                        else if(fs.Tenant__r.Company != null){
                            isrec.Name += fs.Tenant__r.Company;
                            isrec.Link = URL.getOrgDomainUrl().toExternalForm() +'/' + fs.Tenant__c;

                        }
                        
                        
                        
                        isrec.SuiteLink = URL.getOrgDomainUrl().toExternalForm() +'/' + fs.Id;
                        
                         System.debug('RecordTypeName=>');
                        if(fs.RecordTypeId !=null)
                        {
                        isrec.RecordTypeName =Schema.getGlobalDescribe().get('Suites__c').getDescribe().getRecordTypeInfosById().get(fs.RecordTypeId).getName();
                        }
                        System.debug('RecordTypeName=>' + isrec.RecordTypeName);
						isrec.LandlordUse = fs.Landlord_Use__c;
                        isrec.NotTracked =  fs.Not_Tracked__c;
                        isrec.SuiteNumber = 'Suite ' + fs.Suite_Number__c;
                        isrec.SuiteRSF = fs.Suite_RSF__c;
                       // isrec.Vacant = fs.vacant__c;
                        isrec.color = '';
                        
                        /*
                        if(isrec.Vacant=='Yes'){
                            isrec.color='#ddd';
                        }
						*/
                        
                        if(isrec.RecordTypeName == 'Vacancy')
                        {
							  isrec.color='#ddd';
                        }
                        
                       
                        
                        if(isrec.LandlordUse !='N/A' )
                        {
                            isrec.LandlordUse = 'Vacant - ' + isrec.LandlordUse;
                        }
                      
                        isrec.textcolor = '';
                        /*
                        if(fs.Suite_LEXP__c != null){
                            isrec.SuiteLEXP = fs.Suite_LEXP__c.month() + '/' + fs.Suite_LEXP__c.day() + '/' + fs.Suite_LEXP__c.year();
                            String cyear = String.valueOf(fs.Suite_LEXP__c.year());
							Integer year= fs.Suite_LEXP__c.year();
                            if(fs.Suite_LEXP__c < system.today() && isrec.Vacant != 'Yes'){
                                isrec.color='#FFFFFF';
                                isrec.textcolor = '#ff0000';
                            } 
                            else if(year > 2032)
                            {
                                isrec.color='#c00000';
                                isrec.textcolor = 'white';
                            }
                            else {

                                if(ycmap.containsKey(cyear)){
                                    isrec.color = ycmap.get(cyear).color__c;
                                    isrec.textcolor = ycmap.get(cyear).textColor__c;
                                }
                            }
                        }
						*/

                        si.individualSuiteList.add(isrec);
                    }
                    
                     if(si.individualSuiteList.size() > 0)
                       {
                    	Map<String,IndividualSuite> productFamilyMap = new Map<String,IndividualSuite>();
						Map<String,IndividualSuite> productFamilyMapSorted = new Map<String,IndividualSuite>();
						List<String> orderingList = new List<String>();
                        List<IndividualSuite> suitesLetterNumbers = new List<IndividualSuite>();
                        List<Integer> orderingListDecimal = new List<Integer>();
                       
						List<IndividualSuite> sortedQuoteLineItemList = new List<IndividualSuite>();
                        
                        for (IndividualSuite qliObj: si.individualSuiteList){
                            String suiteNo = qliObj.SuiteNumber.right(qliObj.SuiteNumber.length()-6);
                            suiteNo = suiteNo.replaceFirst( '^0+', '');
                            if(suiteNo.isNumeric())
                            {
                        			productFamilyMap.put(suiteNo,qliObj);
                            }
                            else
                            {
                                suitesLetterNumbers.add(qliObj);
                            }
                            
                       
            }

    					//Add all elements of Set into a list
            			orderingList.addAll(productFamilyMap.keyset());

                         for ( Integer j= 0; j < orderingList.size(); j++){
                            
                           orderingListDecimal.add(Integer.valueOf(orderingList[j]));
                            
    }
            			//Sort the List
    					orderingListDecimal.sort();
 						
            			for ( Integer j= 0; j < orderingList.size(); j++){
                            system.debug(orderingList[j]);
                        productFamilyMapSorted.put(String.valueOf(orderingListDecimal[j]),productFamilyMap.get(String.valueOf(orderingListDecimal[j])));
    }
 						
            			//Get the sorted list
            		  si.individualSuiteList = productFamilyMapSorted.values();
                      if(suitesLetterNumbers.size()>0)
                      {
					  si.individualSuiteList.addAll(suitesLetterNumbers);
                          
                      }
                 }
                    
                    if(si.individualSuiteList.size() > 0){
                        si.width = 95*1.0/si.individualSuiteList.size();
                        
                        resp.suiteInfoList.add(si);
                        //added just now this loop
                        Integer heightCell = 0;
                        Integer count =0;
                        Integer MaxHeight = 0;
                        Integer MaxCount = 0;
                        for (IndividualSuite s : si.individualSuiteList){
                            heightCell = 0;
                            /*
                            if(s.Name != null){
                            heightCell = heightCell + 18;
                            count++;

                            }
*/
                            if(s.SuiteNumber != null){
                               
                            heightCell = heightCell + 18;
                            count++;  
                            }
                            if(s.SuiteRSF != null){
                               
                            heightCell = heightCell + 18;
                            count++;   
                            }
                            
                            if(s.LandlordUse != null){
                               
                            heightCell = heightCell + 18;
							count++;
                            }

                            if(s.NotTracked != null){
                               
                            heightCell = heightCell + 18;
							count++;
                            }
                            /*
                            if(s.Address != null){
                               
                            heightCell = heightCell + 18;
                            count++;
                            }
*/
                            /*
                            if(s.Vacant != null){
                            if(s.Vacant == 'Yes')
                            {
                                heightCell = heightCell + 25;
                            count++;
                            }
                            else
                            {
                            heightCell = heightCell + 18;
                            count++; 
                            }
                            }
*/
                            
                            if(heightCell > MaxHeight)
                            {
                                MaxHeight = heightCell;
                            }
                            
                            if( count > MaxCount)
                            {
                                MaxCount = count;
                            }
                        }
                        if(MaxCount >4 && si.individualSuiteList.size() > 8 )
                        {
                            si.height = MaxHeight + 30;
                        }
                        else if(MaxCount >4 && si.individualSuiteList.size() > 15 )
                        {
                            si.height = MaxHeight + 60;
                        }
                        else
                        {
                        si.height = MaxHeight;
                        }
                    }
                   
                }
            }  
        }
        
    }
    
    public class BuildingResponse{
        
        public String Name{get;set;}
        public String Address{get;set;}
        public List<SuiteInfo> suiteInfoList{get;set;}
    }
    
    public class SuiteInfo{
        
        public String FloorNumber{get;set;}
        public Decimal width{get;set;}
        public Decimal height{get;set;}
        public List<IndividualSuite> individualSuiteList{get;set;}
    }
    public class IndividualSuite{
        
        public String color{get;set;}
        public String textcolor{get;set;}
        public String Name{get;set;}
        public String SuiteNumber{get;set;}
        public Decimal SuiteRSF{get;set;}
        public String SuiteLEXP{get;set;}
        public String Address{get;set;}
        public String Vacant{get;set;}
        public String RecordTypeName{get;set;}
        public String LandlordUse{get;set;}
        public String NotTracked{get;set;}
        public String Link{get;set;}
        public String SuiteLink{get;set;}
    }

}