force-app/main/default/objects/Account/fields/Client_Status__c.field-meta.xml
<CustomField>
    <fullName>Client_Status__c</fullName>
    <label>Client Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Commission__c/Commission__c.object-meta.xml
<CustomObject>
    <label>Commission</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Commission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Commission__c.field-meta.xml
<CustomField>
    <fullName>Commission__c</fullName>
    <label>Commission Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Square Footage</fullName>
            </value>
            <value>
                <fullName>Percentage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Deal_Source__c.field-meta.xml
<CustomField>
    <fullName>Deal_Source__c</fullName>
    <label>Deal Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Existing Client</fullName>
            </value>
            <value>
                <fullName>New Business</fullName>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Deal_Value__c.field-meta.xml
<CustomField>
    <fullName>Deal_Value__c</fullName>
    <label>Deal Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/OpportunityTaskTriggerTest.cls
@isTest
public with sharing class OpportunityTaskTriggerTest {
    @isTest
    public static void CreateOpportunityTasksOnUpdate(){
        Date d = Date.newInstance(2000, 2, 20);
        Account ac = new Account(
        Name='test Account',
        Client_Status__c = 'Active');
        insert ac;
        Opportunity op = new Opportunity(
            AccountId=ac.Id,
            Name = 'Test opp',
            Date_Added__c = d,
            Deal_Source__c = 'New Business',
            Commission__c = 'Percentage',
            CloseDate = d,
            Deal_Value__c = 12,
            StageName = 'Commission'
        );
        insert op;
        Task t = [SELECT Subject, WhatId FROM Task LIMIT 1];
        system.Assert(t.Subject == 'Post Close To Do\'s');
        system.Assert(t.WhatId == ac.Id);

    }
    
    @isTest
    public static void CreateOpportunityTasksOnInsert(){
        Date d = Date.newInstance(2000, 2, 20);
        Account ac = new Account(
        Name='test Account',
        Client_Status__c = 'Active');
        insert ac;
        
        Opportunity op2 = new Opportunity(
            AccountId=ac.Id,
            Name = 'Test opp2',
            Date_Added__c = d,
            Deal_Source__c = 'New Business',
            Commission__c = 'Percentage',
            CloseDate = d,
            Deal_Value__c = 12,
            StageName = 'Lease Execution'
        );
        insert op2;
        
        op2.StageName = 'Commission';
        update op2;
        Task t = [SELECT Subject, WhatId FROM Task LIMIT 1];
        system.Assert(t.Subject == 'Post Close To Do\'s');
        system.Assert(t.WhatId == ac.Id);
    }
}