force-app/main/default/objects/Account/fields/Critical_Dates__c.field-meta.xml
<CustomField>
    <fullName>Critical_Dates__c</fullName>
    <label>Critical Dates</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <label>Client</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Critical_Dates__c/Critical_Dates__c.object-meta.xml
<CustomObject>
    <label>Critical Dates</label>
    <nameField>
        <displayFormat>CD-{00000}</displayFormat>
        <label>Critical Dates Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Critical Dates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Critical_Dates__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Critical Dates</relationshipLabel>
    <relationshipName>Critical_Dates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Critical_Dates__c/fields/Advance_Notice__c.field-meta.xml
<CustomField>
    <fullName>Advance_Notice__c</fullName>
    <label>Advance Notice</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>On Date</fullName>
            </value>
            <value>
                <fullName>1 month</fullName>
            </value>
            <value>
                <fullName>3 months</fullName>
            </value>
            <value>
                <fullName>6 months</fullName>
            </value>
            <value>
                <fullName>9 months</fullName>
            </value>
            <value>
                <fullName>12 months</fullName>
            </value>
            <value>
                <fullName>18 months</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Critical_Dates__c/fields/Critical_Date__c.field-meta.xml
<CustomField>
    <fullName>Critical_Date__c</fullName>
    <label>Critical Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Critical_Dates__c/fields/Critical_Date_Type__c.field-meta.xml
<CustomField>
    <fullName>Critical_Date_Type__c</fullName>
    <label>Critical Date Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lease Commencement Date</fullName>
            </value>
            <value>
                <fullName>Lease Expiration Date</fullName>
            </value>
            <value>
                <fullName>Rent Abatement</fullName>
            </value>
            <value>
                <fullName>Rent Increase</fullName>
            </value>
            <value>
                <fullName>TI to Free Rent Conversion</fullName>
            </value>
            <value>
                <fullName>Auto-Renewal Notice Date</fullName>
            </value>
            <value>
                <fullName>Security Deposit Burn Off</fullName>
            </value>
            <value>
                <fullName>Right to Terminate Effective Date</fullName>
            </value>
            <value>
                <fullName>Right to Terminate Notice Opening</fullName>
            </value>
            <value>
                <fullName>Right to Terminate Notice Closing</fullName>
            </value>
            <value>
                <fullName>Right to Renew Opening</fullName>
            </value>
            <value>
                <fullName>Right to Renew Closing</fullName>
            </value>
            <value>
                <fullName>Security Deposit Return</fullName>
            </value>
            <value>
                <fullName>COI Expiration</fullName>
            </value>
            <value>
                <fullName>Notice to Purchase Furniture Due</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CriticalDatesBatch.cls
public class CriticalDatesBatch implements Database.Batchable<sObject>, Database.Stateful{
    
    public String hostURL = System.URL.getSalesforceBaseUrl().getHost();
     public Date todayDate = date.today(); 
    //public Date todayDate = Date.newInstance(2023, 2, 28);
    //templates are not being used now
    // public EmailTemplate template = [Select id,name,subject from EmailTemplate where name='EmailNotificationCriticalDates'];
    // public EmailTemplate templateOnDate = [Select Id, Name, Subject FROM EmailTemplate WHERE Name='EmailOnDate'];
    // public EmailTemplate templateAutoRenewalNoticeDate = [SELECT Id,Name, Subject FROM EmailTemplate WHERE Name='EmailAutoRenewalNotice'];
    public Contact cnt = [select id, Email from Contact where Email != null Limit 1].size()>0 ? [select id, Email from Contact where Email != null Limit 1][0] : null;
    
    public Database.QueryLocator start(Database.BatchableContext bc) {  
        return Database.getQueryLocator(
            [SELECT Name, Critical_Date__c, Critical_Date_Type__c, Advance_Notice__c, Account__r.Owner.Name, Account__r.Owner.Email, Account__r.Owner.Id, Account__r.Name
             FROM  	Critical_Dates__c]
        );
    }


public Boolean isEndOfMonth(Date d) {
    Map<Integer, Integer> numberOfDaysInMonths = new Map<Integer, Integer>{
        1=>31, 2=>28, 3=>31, 4=>30, 5=>31, 6=>30,
        7=>31, 8=>31, 9=>30, 10=>31, 11=>30, 12=>31
    };
    if(numberOfDaysInMonths.containsKey(d.month())) {
        if(numberOfDaysInMonths.get(d.month()) == d.day())
        {
            return true;
        }
        else{
            return false;
        }
    } else {
        return false;
    }
}
    
    public void execute(Database.BatchableContext bc, List<Critical_Dates__c> scope){
        // process each batch of records  
        Map<String, Date> advanceNoticeAndDateMap = new Map<String, Date>{};
        advanceNoticeAndDateMap.put('On Date', todayDate);
        advanceNoticeAndDateMap.put('1 month', todayDate.addMonths(1));
        advanceNoticeAndDateMap.put('3 months', todayDate.addMonths(3));
        advanceNoticeAndDateMap.put('6 months', todayDate.addMonths(6));
        advanceNoticeAndDateMap.put('9 months', todayDate.addMonths(9));
        advanceNoticeAndDateMap.put('12 months', todayDate.addMonths(12));
        advanceNoticeAndDateMap.put('18 months', todayDate.addMonths(18));
        String article = 'a';
        List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();

        for(Critical_Dates__c cd : scope)
        {  
            try{
                String str = (String)cd.Advance_Notice__c;
                if(str == null || String.isBlank((String) str)) {
                    continue;
                }
                List<String> listString = str.split(';');
                Set<String> setString = new Set<String>(listString);
                Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
                message.toAddresses = new String[] { cd.Account__r.Owner.Email }; 
                // message.setTemplateId(templateOnDate.Id);
                if(cnt != null ){
                    message.setTargetObjectId(cnt.id); 
                }
                message.setWhatId(cd.Id);
                message.setSubject('Advance Notice');
                if(cd.Critical_Date_Type__c == 'Auto-Renewal Notice Date') {
                    article = 'an';
                } else {
                    article = 'a';
                }
                for(String s : setString) {
                    if(advanceNoticeAndDateMap.containsKey(s) && cd.Critical_Date__c == advanceNoticeAndDateMap.get(s)){
                        if(s == 'On Date') {
                            message.setHtmlBody('Your client, <a href="'+hostURL+'/lightning/r/Account/'+cd.Account__r.Id+'/view">' + cd.Account__r.Name+'</a>, has '+article+' '+cd.Critical_Date_Type__c+' occurring on '+cd.Critical_Date__c.format() +', today.');
                            emails.add(message);  
                        }
                        else {
                            message.setHtmlBody('Your client, <a href="'+hostURL+'/lightning/r/Account/'+cd.Account__r.Id+'/view">' + cd.Account__r.Name+'</a>, has '+article+' '+cd.Critical_Date_Type__c+' occurring on '+cd.Critical_Date__c.format() +', '+s+' from today.');
                            emails.add(message);  
                        }
                    }
                    if(this.isEndOfMonth(todayDate) && todayDate.day() < 31 && cd.Critical_Date__c.day() > todayDate.day() && s != 'On Date') {
                        if(advanceNoticeAndDateMap.get(s).day() < cd.Critical_Date__c.day() && advanceNoticeAndDateMap.get(s).month() == cd.Critical_Date__c.month()  && advanceNoticeAndDateMap.get(s).Year() == cd.Critical_Date__c.Year()){
                            message.setHtmlBody('Your client, <a href="'+hostURL+'/lightning/r/Account/'+cd.Account__r.Id+'/view">' + cd.Account__r.Name+'</a>, has '+article+' '+cd.Critical_Date_Type__c+' occurring on '+cd.Critical_Date__c.format() +', '+s+' from today.');
                            emails.add(message);  
                        }
                    }
                }
            }
            catch(Exception e){
                System.debug('Critical Dates Error: '+e + ' line number:: '+e.getLineNumber());
            }
        } 
        
        if(emails.size() > 0)
        {
            // Send the emails in a transaction, then roll it back
            Savepoint sp = Database.setSavepoint();
            Messaging.sendEmail(emails); // Dummy email send
            Database.rollback(sp); // Email will not send as it is rolled Back   
            
            List<Messaging.SingleEmailMessage> msgListToBeSend = new List<Messaging.SingleEmailMessage>();
            for (Messaging.SingleEmailMessage email : emails) {
                Messaging.SingleEmailMessage emailToSend = new Messaging.SingleEmailMessage();
                emailToSend.setToAddresses(email.getToAddresses());
                emailToSend.setPlainTextBody(email.getPlainTextBody());
                emailToSend.setHTMLBody(email.getHTMLBody());
                emailToSend.setSubject(email.getSubject());
                msgListToBeSend.add(emailToSend); 
            } 
            Messaging.SendEmailResult[] results = Messaging.sendEmail(msgListToBeSend);  
            Integer invocations = Limits.getEmailInvocations();
            system.debug('invoattions ' + invocations);
        }
    }
    
    
    
    public void finish(Database.BatchableContext bc){
        
    }
}