force-app/main/default/objects/To_Do__c/To_Do__c.object-meta.xml
<CustomObject>
    <label>To Do</label>
    <nameField>
        <label>To Do Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>To Dos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/To_Do__c/fields/Access__c.field-meta.xml
<CustomField>
    <fullName>Access__c</fullName>
    <label>Access</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Private</fullName>
            </value>
            <value>
                <fullName>Public</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/To_Do__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Normal</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/To_Do__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Subject</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/To_Do__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Murray Aronson</fullName>
            </value>
            <value>
                <fullName>Personal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ToDosListingController.cls
public class ToDosListingController {
    
    private static final string BASEQUERY=  'SELECT ID, Name, Subject__c, Due_Date__c, Type__c, Priority_Order__c, Priority__c '+
        'FROM To_Do__c :whereClause';
    
    @AuraEnabled
    public static List<To_Do__c> getToDosList( String filterOrder, boolean publicTodos, String toDosearch) {
        filterOrder.toLowerCase();
        System.debug(filterOrder+ ' ' + publicTodos + toDosearch);
        
        List<To_Do__c> filteredToDoS = new List<To_Do__c>();
        String query = BASEQUERY;
        String searchClause = '';
        //with search field term
        if(toDosearch != null && toDosearch.length() >= 1){
            
            if(filterOrder == 'high' && publicTodos == false){
                searchClause += 'Where Name like \'%' + toDosearch + '%\''+  '  AND Access__c= \'Public\'  AND  OwnerId=\'' +UserInfo.getUserId() +'\''+' ORDER BY Priority_Order__c ASC, Priority__c ASC';
                String    target= ':whereClause'; 
                system.debug('got here c1');
                
                query= query.replace(target, searchClause);
                filteredToDos = Database.query(query);
                System.debug(filteredToDos);
            }
            if(filterOrder == 'low' && publicTodos == false){
                searchClause += 'Where Name like \'%' + toDosearch + '%\' '+ '  AND Access__c= \'Public\'  AND  OwnerId=\'' +UserInfo.getUserId() +'\''+' ORDER BY Priority_Order__c DESC, Priority__c ASC';
                String    target= ':whereClause'; 
                
                query= query.replace(target, searchClause);
                filteredToDos = Database.query(query);
                System.debug(query);
            }
            
            if (filterOrder == 'high' && publicTodos == true ){
                searchClause += 'Where Name like \'%' + toDosearch + '%\''+ '  AND Access__c= \'Public\'' +' ORDER BY Priority_Order__c ASC, Priority__c ASC';
                String    target= ':whereClause'; 
                
                query= query.replace(target, searchClause);
                filteredToDos = Database.query(query);
                System.debug(query);
            }
            if (filterOrder == 'low' && publicTodos == true ){
                searchClause += 'Where Name like \'%' + toDosearch + '%\''+ '  AND Access__c= \'Public\'' +' ORDER BY Priority__c DESC, Priority_Order__c ASC';
                String    target= ':whereClause'; 
                
                query= query.replace(target, searchClause);
                filteredToDos = Database.query(query);
                System.debug(query);
            }
            return filteredToDos; 
            
        }
        
        
        if(toDosearch == null || String.isBlank(toDosearch)){
            
            if (filterOrder == 'high' && publicTodos == false ){
                searchClause += 'Where Due_Date__c= today AND Access__c= \'Public\'  AND  OwnerId=\'' +UserInfo.getUserId() +'\''+'ORDER BY Priority_Order__c ASC, Priority__c ASC';
                String    target= ':whereClause'; 
                
                query= query.replace(target, searchClause);
                System.debug(query);
            }
            if (filterOrder == 'low' && publicTodos == false ){
                searchClause += 'Where Due_Date__c= today AND Access__c= \'Public\'  AND  OwnerId=\'' +UserInfo.getUserId() +'\''+'ORDER BY Priority__c DESC, Priority_Order__c ASC';
                String    target= ':whereClause'; 
                
                query= query.replace(target, searchClause);
                System.debug(query);
            }
            if (filterOrder == 'high' && publicTodos == true ){
                searchClause += 'Where Due_Date__c= today AND Access__c= \'Public\'' +'ORDER BY Priority_Order__c ASC, Priority__c ASC';
                String    target= ':whereClause'; 
                
                query= query.replace(target, searchClause);
                System.debug(query);
            }
            if (filterOrder == 'low' && publicTodos == true ){
                searchClause += 'Where Due_Date__c= today AND Access__c= \'Public\'' +'ORDER BY Priority__c DESC, Priority_Order__c ASC';
                String    target= ':whereClause'; 
                
                query= query.replace(target, searchClause);
                System.debug(query);
                filteredToDos = Database.query(query);
                
            }
            if(filterOrder != null ){
                searchClause += 'Where Due_Date__c= today AND Access__c= \'Public\' AND  OwnerId=\'' + UserInfo.getUserId() +'\''+ ' ORDER BY Priority_Order__c ASC';
                
                String    target= ':whereClause'; 
                
                query= query.replace(target, searchClause);
                filteredToDos = Database.query(query);
            }	        
            
            
            
            
        }
        return filteredToDos; 
    }
    
}