force-app/main/default/objects/To_Do__c/To_Do__c.object-meta.xml
<CustomObject>
    <label>To Do</label>
    <nameField>
        <label>To Do Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>To Dos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/To_Do__c/fields/Access__c.field-meta.xml
<CustomField>
    <fullName>Access__c</fullName>
    <label>Access</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Private</fullName>
            </value>
            <value>
                <fullName>Public</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/To_Do__c/fields/Periodicity__c.field-meta.xml
<CustomField>
    <fullName>Periodicity__c</fullName>
    <label>Periodicity</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yearly</fullName>
            </value>
            <value>
                <fullName>Biannually</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Biweekly</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/To_Do__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Normal</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/To_Do__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Murray Aronson</fullName>
            </value>
            <value>
                <fullName>Personal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TodoListingTest.cls
@isTest public class TodoListingTest {
    @isTest public static  void ToDosListTest() {
        
        
        
        To_Do__c td = new To_Do__c();
        
        td.Access__c ='Public';
        td.Due_Date__c= Date.today();
        td.Type__c= 'Murray Aronson';
        td.Name= 'Test';
        td.Priority__c = 'High';
        td.Periodicity__c= 'Daily';
        
        insert td;
        
        List<To_Do__c>  getToDos = ToDosListingController.getToDosList('Low', true, null);
        List<To_Do__c>  getTodoWithPriorityWithOutOwnerWithNullQuery = ToDosListingController.getToDosList('Low', true, 'hen');
        List<To_Do__c>  getToDosWithNullQuery = ToDosListingController.getToDosList('Low', false, null);
        List<To_Do__c>  getToDosOwner = ToDosListingController.getToDosList('Low', false, 'hen');      
        
        List<To_Do__c>  getTodo = ToDosListingController.getToDosList('High', true, 'hj');
        List<To_Do__c>  getTodoOwnerWithNullQuery = ToDosListingController.getToDosList('High', false, null);
        List<To_Do__c>  getTodoWithPriorityOwnerWithNullQuery = ToDosListingController.getToDosList('High', true, null);
        List<To_Do__c>  getTodoOwner = ToDosListingController.getToDosList('High', false, 'hen');
        
        
    }         
    
}