force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Costar_Report__c/Costar_Report__c.object-meta.xml
<CustomObject>
    <label>Costar Report</label>
    <nameField>
        <label>Costar Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Costar Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Costar_Report__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <referenceTo>City__c</referenceTo>
    <relationshipLabel>Costar Reports</relationshipLabel>
    <relationshipName>Costar_Reports1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Costar_Report__c/fields/Costar_Report_Date__c.field-meta.xml
<CustomField>
    <fullName>Costar_Report_Date__c</fullName>
    <label>Costar Report Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/HanlderCostarReportName.cls
public class HanlderCostarReportName {
    
    public static void ChangeCostarReportNameOnInsert(List<Costar_Report__c> reportsList)
    {
			List<Costar_Report__c> reportsNameToUpdate = new List<Costar_Report__c>();
        
            Set<Id> reportRelatedCitiesId = new Set<Id>();
        
        
        	if(reportsList.size()>0)
            {
             
            		for(Costar_Report__c Obj : reportsList)
            			{
							reportRelatedCitiesId.add(Obj.City__c);
            			}
            	}
        
            map<Id, City__c> cities = new Map<Id,City__c>([Select Id, Name from City__c where Id IN :reportRelatedCitiesId]);
          
            if(reportsList.size()>0)
            {
                
				for(Costar_Report__c reportObj : reportsList)
                {
                    City__c  cityName = cities.get(reportObj.City__c);
                    String reportDate = reportObj.Costar_Report_Date__c.month() + '/' + reportObj.Costar_Report_Date__c.day() + '/' + reportObj.Costar_Report_Date__c.year();
                    String reportName = cityName.Name + ' Costar Report ' + reportDate;
                    Costar_Report__c newobj = new Costar_Report__c();
                    newobj.Id = reportObj.Id;
                    newobj.Name = reportName;
                    reportsNameToUpdate.add(newobj);  
                }
            }
        if(reportsNameToUpdate.size()>0)
        {
			update reportsNameToUpdate;
        }
    }

}