force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/City__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>HYPERLINK( &apos;/lightning/r/Market__c/&apos; + Submarket__r.Market__r.Id + &apos;/view&apos; ,  Submarket__r.Market__r.Name )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/City__c/fields/Submarket__c.field-meta.xml
<CustomField>
    <fullName>Submarket__c</fullName>
    <label>Submarket</label>
    <referenceTo>Submarket__c</referenceTo>
    <relationshipLabel>Cities</relationshipLabel>
    <relationshipName>Cities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Market__c/Market__c.object-meta.xml
<CustomObject>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Submarket__c/Submarket__c.object-meta.xml
<CustomObject>
    <label>Submarket</label>
    <nameField>
        <label>Submarket Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Submarkets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Submarket__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <label>Market</label>
    <referenceTo>Market__c</referenceTo>
    <relationshipLabel>Submarkets</relationshipLabel>
    <relationshipName>Submarkets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TestMarketSubmarketCityController.cls
@isTest
private class TestMarketSubmarketCityController{
    
    @isTest
    static void TestGetMarketName()
    {
        Market__c marketObj = new  Market__c(Name='test market');
       insert marketObj;
       String marketName = MarketSubmarketCityController.getMarketName(marketObj.Id);
       System.assertEquals('test market',marketName,'Market Name should be same');
    }

    @isTest
    static void TestGetMarketRelatedSubmarkets()
    {
        Market__c marketObj = new  Market__c(Name='test market');
       insert marketObj;
       Submarket__c newSubMarketObj =   new  Submarket__c(Name='test Sub-market',Market__c= marketObj.Id);
       insert newSubMarketObj;
       List<Submarket__c> submarketList = MarketSubmarketCityController.getMarketRelatedSubMarkets(marketObj.Id);
       System.assertEquals(1,submarketList.size(),'Submarket count should be 1');
    }

    @isTest
    static void TestGetSubMarketRelatedCities()
    {
        Market__c marketObj = new  Market__c(Name='test market');
       insert marketObj;
       Submarket__c newSubMarketObj =   new  Submarket__c(Name='test Sub-market',Market__c= marketObj.Id);
       insert newSubMarketObj;
       City__c newCityObj = new City__c(Name='test City',Submarket__c= newSubMarketObj.Id);
       insert newCityObj;
       List<City__c> CitiesList = MarketSubmarketCityController.getSubMarketRelatedCities(newSubMarketObj.Id);
       System.assertEquals(1,CitiesList.size(),'Cities count should be 1');
    }

    @isTest
    static void TestGetMarketNameException()
    {
       try 
        {
            String marketName = MarketSubmarketCityController.getMarketName('1233xxxx');
        }
       catch (Exception e) {
        System.assertEquals(false,e.getMessage().contains('List has no rows for assignment to SObject'));
       }
    }

}