force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/City__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>HYPERLINK( &apos;/lightning/r/Market__c/&apos; + Submarket__r.Market__r.Id + &apos;/view&apos; ,  Submarket__r.Market__r.Name )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/City__c/fields/Submarket__c.field-meta.xml
<CustomField>
    <fullName>Submarket__c</fullName>
    <label>Submarket</label>
    <referenceTo>Submarket__c</referenceTo>
    <relationshipLabel>Cities</relationshipLabel>
    <relationshipName>Cities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Market__c/Market__c.object-meta.xml
<CustomObject>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Submarket__c/Submarket__c.object-meta.xml
<CustomObject>
    <label>Submarket</label>
    <nameField>
        <label>Submarket Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Submarkets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Submarket__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <label>Market</label>
    <referenceTo>Market__c</referenceTo>
    <relationshipLabel>Submarkets</relationshipLabel>
    <relationshipName>Submarkets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/MarketSubmarketCityController.cls
public with sharing class MarketSubmarketCityController {
    
    @AuraEnabled
    public static String getMarketName(string recordId)
    {
        Market__c obj = [Select Id, Name from Market__c where Id =:recordId];
        system.debug(' obj => '+ obj);
        return obj.Name;
    }
    
    
     @AuraEnabled
    public static List<Submarket__c> getMarketRelatedSubMarkets(string recordId)
    {
        List<Submarket__c> submarketList = [Select Id, Name from Submarket__c where Market__c =:recordId];
        system.debug(' submarketList => '+ submarketList);
        return submarketList;
    }
    
     @AuraEnabled
    public static List<City__c> getSubMarketRelatedCities(string recordId)
    {
        List<City__c> CitiesList = [Select Id, Name from City__c where Submarket__c =:recordId];
        system.debug(' CitiesList => '+ CitiesList);
        return CitiesList;
    }

}