force-app/main/default/objects/Building__c/Building__c.object-meta.xml
<CustomObject>
    <label>Building</label>
    <nameField>
        <label>Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Building__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <label>Market (not used)</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StatePK__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Los Angeles</fullName>
            </value>
            <value>
                <fullName>Orange County</fullName>
            </value>
            <value>
                <fullName>San Francisco</fullName>
            </value>
            <value>
                <fullName>San Jose</fullName>
            </value>
            <value>
                <fullName>San Diego</fullName>
            </value>
            <value>
                <fullName>Ventura County</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Building__c/fields/Primary_Broker__c.field-meta.xml
<CustomField>
    <fullName>Primary_Broker__c</fullName>
    <label>Brokers</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Building_Brokers__c/Building_Brokers__c.object-meta.xml
<CustomObject>
    <description>To handle brokers related to buildings and tenants</description>
    <label>Listed Building</label>
    <nameField>
        <displayFormat>B{00000}</displayFormat>
        <label>Broker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Listed Buildings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Building_Brokers__c/fields/Broker__c.field-meta.xml
<CustomField>
    <fullName>Broker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Broker</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.Name</field>
            <operation>equals</operation>
            <value>Broker</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipName>BuildingBrokers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Building_Brokers__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Listing Brokers</relationshipLabel>
    <relationshipName>Brokers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/City__c/fields/Continent__c.field-meta.xml
<CustomField>
    <fullName>Continent__c</fullName>
    <label>Continent</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Africa</fullName>
            </value>
            <value>
                <fullName>Asia</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
            </value>
            <value>
                <fullName>North America</fullName>
            </value>
            <value>
                <fullName>South America</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/City__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>HYPERLINK( &apos;/lightning/r/Market__c/&apos; + Submarket__r.Market__r.Id + &apos;/view&apos; ,  Submarket__r.Market__r.Name )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Market__c/Market__c.object-meta.xml
<CustomObject>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Market__c/fields/Continent__c.field-meta.xml
<CustomField>
    <fullName>Continent__c</fullName>
    <label>Continent</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Africa</fullName>
            </value>
            <value>
                <fullName>Asia</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
            </value>
            <value>
                <fullName>North America</fullName>
            </value>
            <value>
                <fullName>South America</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Market__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Continent__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USA</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>United States</fullName>
            </value>
            <value>
                <fullName>Mexico</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>England</fullName>
            </value>
            <value>
                <fullName>Guatemala</fullName>
            </value>
            <value>
                <fullName>Cuba</fullName>
            </value>
            <value>
                <fullName>Haiti</fullName>
            </value>
            <value>
                <fullName>Dominican Republic</fullName>
            </value>
            <value>
                <fullName>Honduras</fullName>
            </value>
            <value>
                <fullName>Nicaragua</fullName>
            </value>
            <value>
                <fullName>El Salvador</fullName>
            </value>
            <value>
                <fullName>Costa Rica</fullName>
            </value>
            <value>
                <fullName>Panama</fullName>
            </value>
            <value>
                <fullName>Jamaica</fullName>
            </value>
            <value>
                <fullName>Trinidad and Tobago</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Saint Lucia</fullName>
            </value>
            <value>
                <fullName>Grenada</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Dominica</fullName>
            </value>
            <value>
                <fullName>Greenland</fullName>
            </value>
            <value>
                <fullName>Saint Kitts and Nevis</fullName>
            </value>
            <value>
                <fullName>South America Country 1</fullName>
            </value>
            <value>
                <fullName>South America Country 2</fullName>
            </value>
            <value>
                <fullName>South America Country 3</fullName>
            </value>
            <value>
                <fullName>Europe Country 1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Submarket__c/Submarket__c.object-meta.xml
<CustomObject>
    <label>Submarket</label>
    <nameField>
        <label>Submarket Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Submarkets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Submarket__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Continent__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USA</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>United States</fullName>
            </value>
            <value>
                <fullName>Mexico</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>England</fullName>
            </value>
            <value>
                <fullName>Guatemala</fullName>
            </value>
            <value>
                <fullName>Cuba</fullName>
            </value>
            <value>
                <fullName>Haiti</fullName>
            </value>
            <value>
                <fullName>Dominican Republic</fullName>
            </value>
            <value>
                <fullName>Honduras</fullName>
            </value>
            <value>
                <fullName>Nicaragua</fullName>
            </value>
            <value>
                <fullName>El Salvador</fullName>
            </value>
            <value>
                <fullName>Costa Rica</fullName>
            </value>
            <value>
                <fullName>Panama</fullName>
            </value>
            <value>
                <fullName>Jamaica</fullName>
            </value>
            <value>
                <fullName>Trinidad and Tobago</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Saint Lucia</fullName>
            </value>
            <value>
                <fullName>Grenada</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Dominica</fullName>
            </value>
            <value>
                <fullName>Greenland</fullName>
            </value>
            <value>
                <fullName>Saint Kitts and Nevis</fullName>
            </value>
            <value>
                <fullName>South America Country 1</fullName>
            </value>
            <value>
                <fullName>South America Country 2</fullName>
            </value>
            <value>
                <fullName>South America Country 3</fullName>
            </value>
            <value>
                <fullName>Europe Country 1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Submarket__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <label>Market</label>
    <referenceTo>Market__c</referenceTo>
    <relationshipLabel>Submarkets</relationshipLabel>
    <relationshipName>Submarkets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Suites__c/Suites__c.object-meta.xml
<CustomObject>
    <label>Suites</label>
    <nameField>
        <displayFormat>SU-{0000}</displayFormat>
        <label>Suite Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Suites</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Suites__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Suites</relationshipLabel>
    <relationshipName>Suites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/QueryTaskDataTest.cls
@isTest
public with sharing class QueryTaskDataTest {
    @isTest
    public static void TestQueryTask() {
        Building__c building1 = new Building__c();
        building1.Name = 'abc';
        insert building1;
        building1 = [SELECT Name FROM Building__c][0];
        //QueryTaskData.getBuildingTasksData(building1.Id);
        Suites__c suite1 = new Suites__c(Building__c=building1.Id);
        insert suite1;
        suite1 = [SELECT Name FROM Suites__c][0];
        Task t1 = new Task(WhatId=suite1.Id);
        Task t2 = new Task(WhatId=building1.Id);
        insert t1;
        insert t2;
        List<Task> taskList = QueryTaskData.getBuildingTasksData(building1.Id);
        System.assertEquals(2, taskList.size());
    }
    
    @isTest
    public static void TestBrokerTasks() {
        Contact c1 = new Contact(LastName='testBroker');
        insert c1;
        c1 = [SELECT Name FROM Contact][0];
        Building__c building1 = new Building__c();
        building1.Name = 'abc';
        building1.Primary_Broker__c = c1.Id;
        insert building1;
        //Contact c1 = new Contact(LastName='testBroker');
        //insert c1;
        building1 = [SELECT Name FROM Building__c][0];
        //QueryTaskData.getBuildingTasksData(building1.Id);
        Suites__c suite1 = new Suites__c(Building__c=building1.Id);
        insert suite1;
        Building_Brokers__c buildingBroker1 = new Building_Brokers__c(Broker__c=c1.Id, Building__c=building1.Id);
        //insert buildingBroker1;
        suite1 = [SELECT Name FROM Suites__c][0];
        Task t1 = new Task(WhatId=suite1.Id);
        Task t2 = new Task(WhatId=building1.Id);
        insert t1;
        insert t2;
        List<Task> taskList = QueryTaskData.QueryBrokerTasks(c1.Id);
        //System.assertEquals(1, taskList.size());
    }
    
    @isTest
    public static void QueryCityTasksTest(){
        Market__c market1 = new Market__c(Continent__c='North America', Country__c='United States', State_Territory__c='AK');
        insert market1;
        Submarket__c submarket = new Submarket__c(Continent__c='North America', Country__c='United States', State_Territory__c='AK', Market__c = market1.Id);
        insert submarket;
        City__c city = new City__c(Continent__c='North America', Country__c='United States', State_Territory__c='AK', Submarket__c = submarket.Id);
        insert city;
        
        Building__c building1 = new Building__c(
            Name = 'abc', 
            Continent__c='North America', 
            Country__c='United States', 
            StatePK__c='AK',
            City_Lookup__c=city.Id,
            Market_Lookup__c = market1.Id,
            Submarket_Lookup__c = submarket.Id
        );
        insert building1;
        
        Task t1 = new Task(Subject='test task', WhatId = building1.Id);
        insert t1;
        
        List<Task> taskList = QueryTaskData.QueryCityTasks(city.Id);
    }
    
    @isTest
    public static void getBuildingsRelatedToSuitesTest(){
        Building__c building1 = new Building__c();
        building1.Name = 'abc';
        insert building1;

        Suites__c suite1 = new Suites__c(Building__c=building1.Id);
        insert suite1;

        Task t1 = new Task(WhatId=suite1.Id);
        Task t2 = new Task(WhatId=building1.Id);
        insert t1;
        insert t2;
        Map<Id,Building__c> taskListMap = QueryTaskData.getBuildingsRelatedToSuites(new List<Id> {suite1.Id});
        system.Assert(taskListMap.get(suite1.Id).Name == building1.Name);
        System.Assert(taskListMap.size()>0);
    }
    
    @isTest
    public static void getSuiteTasksTest(){
        Building__c building1 = new Building__c();
        building1.Name = 'abc';
        insert building1;

        Suites__c suite1 = new Suites__c(Building__c=building1.Id);
        insert suite1;

        Task t1 = new Task(WhatId=suite1.Id);
        insert t1;
        
        List<Task> taskList = QueryTaskData.getSuiteTasks(suite1.Id);
        
        system.Assert(taskList.size()>0);
    }
}