force-app/main/default/objects/Building__c/Building__c.object-meta.xml
<CustomObject>
    <label>Building</label>
    <nameField>
        <label>Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Flyers__c/Flyers__c.object-meta.xml
<CustomObject>
    <label>Building Flyer</label>
    <nameField>
        <displayFormat>F-{0000}</displayFormat>
        <label>Flyer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Flyers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Flyers__c/fields/Active_or_Inactive__c.field-meta.xml
<CustomField>
    <fullName>Active_or_Inactive__c</fullName>
    <label>Active or Inactive</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Flyers__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipName>Flyers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Flyers__c/fields/Flyer_Date__c.field-meta.xml
<CustomField>
    <fullName>Flyer_Date__c</fullName>
    <inlineHelpText>Input date you received flyer from source</inlineHelpText>
    <label>Flyer Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Flyers__c/fields/Flyer_Type__c.field-meta.xml
<CustomField>
    <fullName>Flyer_Type__c</fullName>
    <label>Flyer Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Sublease</fullName>
            </value>
            <value>
                <fullName>Coworking</fullName>
            </value>
            <value>
                <fullName>Sale</fullName>
            </value>
            <value>
                <fullName>Direct and Sale</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/HandlerTriggerForFlyerInsert.cls
public class HandlerTriggerForFlyerInsert {
    
    

    public static void UpdateDirectFlyerStatus(List<Flyers__c> FlyersList)
        
    {
        Flyers__c FlyerObj = FlyersList[0];


        
        if(CheckFlyerDateRecentOrNot(FlyerObj))
        {
        
           
			if((FlyerObj.Flyer_Type__c == 'Direct' || FlyerObj.Flyer_Type__c == 'Sale') && FlyerObj.Active_or_Inactive__c=='Active')
            {
                
                
                List<Flyers__c> AllFlyersRelatedToBuilding = [Select Id,Name, building__c,Active_or_Inactive__c,Flyer_Date__c,
                                                              Flyer_Type__c
                                                              from Flyers__c where building__c =:FlyerObj.Building__c 
                                                              AND ID != :FlyerObj.Id
                                                             ];
                
                
                
                
                List<Flyers__c> FlyersNeedToUpdate = new List<Flyers__c>();
                
                if(AllFlyersRelatedToBuilding!=NULL)
                {
                  
                for(Flyers__c obj : AllFlyersRelatedToBuilding)
                {
                    if((FlyerObj.Flyer_Type__c == 'Direct' || FlyerObj.Flyer_Type__c == 'Sale') && obj.Active_or_Inactive__c == 'Active')
                    {
                        	
							obj.Active_or_Inactive__c = 'Inactive';
                        	FlyersNeedToUpdate.add(obj);
                    }
                }
                    
                }
                
               
                
                
                if(FlyersNeedToUpdate!=NULL)
                {
                    UpdationClassForFlyer.isfutureupdate=true;
					update FlyersNeedToUpdate;
                }

            }
            
        
        
        }
        
        
      	else 
        {
          
            if((FlyerObj.Flyer_Type__c == 'Direct' || FlyerObj.Flyer_Type__c == 'Sale') && FlyerObj.Active_or_Inactive__c=='Active')
            {
                
                List<Flyers__c> AllFlyersRelatedToBuilding = [Select Id,Name, building__c,Active_or_Inactive__c,Flyer_Date__c,
                                                              Flyer_Type__c
                                                              from Flyers__c where building__c =:FlyerObj.Building__c 
                                                              AND ID = :FlyerObj.Id
                                                             ];
                
              
                
                
                List<Flyers__c> FlyersNeedToUpdate = new List<Flyers__c>();
                
                if(AllFlyersRelatedToBuilding!=NULL)
                {
                  
                for(Flyers__c obj : AllFlyersRelatedToBuilding)
                {
                    if((FlyerObj.Flyer_Type__c == 'Direct' || FlyerObj.Flyer_Type__c == 'Sale') && obj.Active_or_Inactive__c == 'Active')
                    {
                        	
							obj.Active_or_Inactive__c = 'Inactive';
                        	FlyersNeedToUpdate.add(obj);
                    }
                }
                    
                }
                
               
                if(FlyersNeedToUpdate!=NULL)
                {
                    UpdationClassForFlyer.isfutureupdate=true;
					update FlyersNeedToUpdate;
                    
                }
            }

        }
    }
    
     public static Boolean CheckFlyerDateRecentOrNot(Flyers__c Obj)
     {
         
		List<Flyers__c> flyersList = [Select Id,Name, building__c,Active_or_Inactive__c,Flyer_Date__c,
                                      Flyer_Type__c
                                      from Flyers__c where building__c =:Obj.Building__c AND Flyer_Date__c > :Obj.Flyer_Date__c AND Flyer_Type__c IN ('Direct','Sale')];
         
         
      if(flyersList.size()>0)
     {
        return false;
     }
      else
    {
        return true;
    }

     }
   
    
   
    
}