force-app/main/default/objects/Building__c/Building__c.object-meta.xml
<CustomObject>
    <label>Building</label>
    <nameField>
        <label>Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Suites__c/Suites__c.object-meta.xml
<CustomObject>
    <label>Suites</label>
    <nameField>
        <displayFormat>SU-{0000}</displayFormat>
        <label>Suite Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Suites</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Suites__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Suites</relationshipLabel>
    <relationshipName>Suites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/NewSuitePhotoController.cls
public with sharing class NewSuitePhotoController {
    
    @AuraEnabled
    public static Suites__c getSuiteNameFromId(Id suitesId){
        try {
            Suites__c suite = [SELECT Name,Building__c FROM Suites__c WHERE Id=:suitesId LIMIT 1];
            return suite;
        } catch (Exception e) {
            system.debug(e);
            throw new AuraHandledException(e.getMessage());
        }
    }
    
     @AuraEnabled
    public static Suite_Photos__c saveSuitePhoto( Suite_Photos__c SuitePhoto) {
        upsert SuitePhoto;   
        return SuitePhoto;   
    }

    
    @AuraEnabled
    public static Boolean attachFilesSuitePhoto( Suite_Photos__c SuitePhoto, List<String> docIds) {
        List<ContentDocumentLink> docLinkList = new List<ContentDocumentLink>();
        //Map<Id,ContentDocument> CDMap = new Map<Id,ContentDocument>([SELECT Title FROM ContentDocument WHERE Id IN :docIds]);

        try{
            for(String docId : docIds){
                
                ContentDocumentLink docLink = new ContentDocumentLink();
                docLink.ContentDocumentId = docId;
                docLink.linkedEntityId = SuitePhoto.Id;
                docLink.sharetype = 'I';
                docLink.visibility = 'AllUsers';
                docLinkList.add(docLink);
               
            }
            upsert docLinkList;
            return true;
        }
        catch(Exception e){
            return false;
        }
	
    }
    

}