force-app/main/default/objects/Building__c/Building__c.object-meta.xml
<CustomObject>
    <label>Building</label>
    <nameField>
        <label>Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Suites__c/Suites__c.object-meta.xml
<CustomObject>
    <label>Suites</label>
    <nameField>
        <displayFormat>SU-{0000}</displayFormat>
        <label>Suite Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Suites</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Suites__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Suites</relationshipLabel>
    <relationshipName>Suites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Video__c/Video__c.object-meta.xml
<CustomObject>
    <label>Video</label>
    <nameField>
        <displayFormat>V-{0000}</displayFormat>
        <label>Videos Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Videos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Video__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Videos</relationshipLabel>
    <relationshipName>Videos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Video__c/fields/Suites__c.field-meta.xml
<CustomField>
    <fullName>Suites__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Suites</label>
    <referenceTo>Suites__c</referenceTo>
    <relationshipLabel>Videos</relationshipLabel>
    <relationshipName>Videos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/NewVideoController.cls
public with sharing class NewVideoController {
    
    @AuraEnabled
    public static Suites__c getSuiteNameFromId(Id suitesId){
        try {
            Suites__c suite = [SELECT Name,Building__c FROM Suites__c WHERE Id=:suitesId LIMIT 1];
            return suite;
        } catch (Exception e) {
            system.debug(e);
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    
    @AuraEnabled
    public static Video__c saveVideo( Video__c video) {
        upsert video;   
        return video;   
    }

    
     @AuraEnabled
    public static Boolean attachFile( Video__c video, String docId) {
        try{
        
			ContentDocumentLink docLink = new ContentDocumentLink();
			doclink.ContentDocumentId = docId;
			doclink.linkedEntityId = video.Id;
			doclink.sharetype = 'I';
			doclink.visibility = 'AllUsers';
			upsert doclink;

            return true;
        }
        catch(Exception e){
            return false;
        }
	
    }
    

}