force-app/main/default/objects/Building__c/Building__c.object-meta.xml
<CustomObject>
    <label>Building</label>
    <nameField>
        <label>Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Floor_Plan__c/Floor_Plan__c.object-meta.xml
<CustomObject>
    <label>Floor Plan</label>
    <nameField>
        <displayFormat>FP-{0000}</displayFormat>
        <label>Floor Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Floor Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Floor_Plan__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Floor Plans</relationshipLabel>
    <relationshipName>Floor_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Floor_Plan__c/fields/File_Location_Formula__c.field-meta.xml
<CustomField>
    <fullName>File_Location_Formula__c</fullName>
    <label>File Location Formula</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Floor_Plan__c/fields/File_Name_Formula__c.field-meta.xml
<CustomField>
    <fullName>File_Name_Formula__c</fullName>
    <label>File Name Formula</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Floor_Plan__c/fields/Floor_Plan_Type__c.field-meta.xml
<CustomField>
    <fullName>Floor_Plan_Type__c</fullName>
    <label>Floor Plan Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Original</fullName>
            </value>
            <value>
                <fullName>Scrubbed</fullName>
            </value>
            <value>
                <fullName>MA Branded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Floor_Plan__c/fields/Suites__c.field-meta.xml
<CustomField>
    <fullName>Suites__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Suites</label>
    <referenceTo>Suites__c</referenceTo>
    <relationshipLabel>Floor Plans</relationshipLabel>
    <relationshipName>Floor_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Suites__c/Suites__c.object-meta.xml
<CustomObject>
    <label>Suites</label>
    <nameField>
        <displayFormat>SU-{0000}</displayFormat>
        <label>Suite Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Suites</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Suites__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Suites</relationshipLabel>
    <relationshipName>Suites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Suites__c/fields/Floor_Plan__c.field-meta.xml
<CustomField>
    <fullName>Floor_Plan__c</fullName>
    <label>Floor Plan</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>No Plan Exists</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/NewFloorPlanController.cls
public with sharing class NewFloorPlanController {

    @AuraEnabled 
    public static Map<String, String> getFloorPlanTypeValues(){
        Map<String, String> options = new Map<String, String>();
        
        Schema.DescribeFieldResult fieldResult = Floor_Plan__c.Floor_Plan_Type__c.getDescribe();
        
        List<Schema.PicklistEntry> pValues = fieldResult.getPicklistValues();
        for (Schema.PicklistEntry p: pValues) {
            
            options.put(p.getValue(), p.getLabel());
        }
        return options;
    }

    @AuraEnabled
    public static String getBuildingIdFromSuiteId(Id suiteId){
        Suites__c suite = [SELECT Id, Building__c FROM Suites__c WHERE Id =:suiteId LIMIT 1];
        if(suite != null){
            return suite.Building__c;
        }
        return '';
    }

    @AuraEnabled
    public static Floor_Plan__c saveFloorPlan( Floor_Plan__c floorPlan) {
        upsert floorPlan;   
        return floorPlan;   
    }

    @AuraEnabled
    public static Boolean attachFile( Floor_Plan__c floorPlan, String docId) {
        try{
            String fileName = '';
            List<ContentDocument> CDList = [SELECT Title FROM ContentDocument WHERE Id =: docId LIMIT 1];
            if(CDList.size()>0){
                fileName = CDList[0].Title;
            }
            floorPlan.File_Location_Formula__c = '/lightning/r/ContentDocument/'+docId+'/view';
            floorPlan.File_Name_Formula__c = fileName;
            update floorPlan;

			ContentDocumentLink docLink = new ContentDocumentLink();
			doclink.ContentDocumentId = docId;
			doclink.linkedEntityId = floorPlan.Id;
			doclink.sharetype = 'I';
			doclink.visibility = 'AllUsers';
			upsert doclink;

            ContentDocument cd = [SELECT Title FROM ContentDocument WHERE Id =: docId];
            cd.Title = floorPlan.Name;
            update cd;
            return true;
        }
        catch(Exception e){
            return false;
        }
    }

    @AuraEnabled
    public static ContentDocument getContentDocumentById(String contentDocumentId){
        List<ContentDocument> contentDocList = new List<ContentDocument>();
        contentDocList = [SELECT Id, Title, ContentSize, CreatedDate, FileType FROM ContentDocument WHERE Id =:contentDocumentId LIMIT 1];
        if(contentDocList.size()>1){
            return contentDocList[0];
        } else{
            return new ContentDocument();
        }
    }

}