force-app/main/default/objects/Building__c/Building__c.object-meta.xml
<CustomObject>
    <label>Building</label>
    <nameField>
        <label>Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Building_Photo__c/Building_Photo__c.object-meta.xml
<CustomObject>
    <label>Building Photo</label>
    <nameField>
        <displayFormat>BP-{00000}</displayFormat>
        <label>Building Photo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Building Photos</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Building_Photo__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Building Photos</relationshipLabel>
    <relationshipName>Building_Photos</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Building_Photo__c/fields/Building_Photo_Date__c.field-meta.xml
<CustomField>
    <fullName>Building_Photo_Date__c</fullName>
    <label>Building Photo Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/PictureControllerTest.cls
@istest 
public class PictureControllerTest 
{
    
    @istest static void testSaveAttachment()
    {
        building__c b = new building__c (Name='test1');
        insert b;
        
        
        
        //building_photo__c bp = new building_photo__c (name = 'test' , building__c = b.id);
        building_photo__c bp = new building_photo__c (building__c = b.id, Building_Photo_Date__c=date.today());
        //building_photo__c bp = new building_photo__c (building__c = b.id);
        
        insert bp;
        
        ContentVersion content=new ContentVersion(); 
        content.Title='Header_Picture1'; 
        content.PathOnClient='/' + content.Title + '.jpg'; 
        Blob bodyBlob=Blob.valueOf('Unit Test ContentVersion Body'); 
        content.VersionData=bodyBlob; 
        //content.LinkedEntityId=sub.id;
        content.origin = 'H';
        insert content;
        
        ContentDocumentLink contentlink=new ContentDocumentLink();
        contentlink.LinkedEntityId=bp.id;
        contentlink.contentdocumentid=[select contentdocumentid from contentversion where id =: content.id].contentdocumentid;
        contentlink.ShareType = 'V';
        test.starttest();
        insert contentlink;
        
        PictureController.getProfilePicture(b.id);
        
    }
}