force-app/main/default/objects/Building__c/Building__c.object-meta.xml
<CustomObject>
    <label>Building</label>
    <nameField>
        <label>Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Building__c/fields/Full_Address__c.field-meta.xml
<CustomField>
    <fullName>Full_Address__c</fullName>
    <formula>LOWER( Name)   &amp;  LOWER(City__c )&amp;  LOWER(text(StatePK__c))</formula>
    <inlineHelpText>This field will be automatically created based on the Address, City and State fields that are input above.</inlineHelpText>
    <label>Full Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Building__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State - do not use</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/building_lead__c/building_lead__c.object-meta.xml
<CustomObject>
    <description>Related Building with Leads</description>
    <label>Building-Tenant Old</label>
    <nameField>
        <label>Building-Tenant Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Building-Tenants Old</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/building_lead__c/fields/Building_BL__c.field-meta.xml
<CustomField>
    <fullName>Building_BL__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Related Building - Lead</description>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipName>building_leads</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/building_lead__c/fields/Building_Lead__c.field-meta.xml
<CustomField>
    <fullName>Building_Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Building</description>
    <label>Tenant</label>
    <referenceTo>Lead</referenceTo>
    <relationshipName>building_leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Lead/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Full_Address__c.field-meta.xml
<CustomField>
    <fullName>Full_Address__c</fullName>
    <formula>LOWER( Property_Address__c) &amp; LOWER(City__c)&amp; LOWER(Text(State__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Full Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Country__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NC</fullName>
            </value>
            <value>
                <fullName>ND</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LeadTriggerHelper.cls
public class LeadTriggerHelper {
    
    //@InvocableMethod
    public static void unlinkBuilding(List<Lead> LeadIds){
        
     Set<String> LeadIdSet = new Set<String>();   
     List<building_lead__c> UnlinkBuilding = new List<building_lead__c>();
     
      for (Lead ld: LeadIds){
            
          if (ld.IsConverted == true && !LeadIdSet.contains(ld.id)) {
                LeadIdSet.add(ld.id);
                system.debug('LeadIdSet' + LeadIdSet);
          }
      }  
        
          if(!LeadIdSet.isempty()){      
             List<building_lead__c> ListBuilead = [SELECT id, building_lead__c  FROM building_lead__c WHERE building_lead__c  in: LeadIdSet];
                 system.debug('ListLeadSet' + ListBuilead);
             for (building_lead__c bl: ListBuilead) {
                 UnlinkBuilding.add(bl);
                 system.debug('AssingUnlinkBuilding' + UnlinkBuilding);
            }   
          }
        
         If(!UnlinkBuilding.isEmpty()){          
          delete UnlinkBuilding;
          system.debug('EndUnlink' + UnlinkBuilding);   
         }    
   }    
   
    public static void DeleteContact(set<id> setContact)
    {
        List<Contact> ContactList = [select id from contact where id = :setContact];
        If(!ContactList.isEmpty())
        {
            delete ContactList;
        } 
    }
    
    public static void InsertBuilding(list<Lead> LeadList)
    {
        MAP<string,id> leadAddMap = new MAP<string,id>();
        for(lead l : leadlist)
        {
            
            /*string street = String.isNotBlank(l.Street) ?  l.Street : '';
            string city =string.isNotBlank(l.City__c) ?  l.City__c : '';
            string state = string.isNotBlank(l.State__c) ?  l.State__c : '';
            string s = street + city+ state;
            System.debug('s'+s);*/
             if ( string.isNotBlank(l.Full_Address__c) && !l.IsConverted == true)
           		 leadAddMap.put(l.Full_Address__c.toLowerCase() ,l.id );
        }
          System.debug('leadAddMap'+leadAddMap);
        list<building_lead__c> OLeadlist = new list<building_lead__c>();
        for(Building__c oBuild : [select id,Full_Address__c from Building__c where Full_Address__c = :leadAddMap.keyset() ])
        {
            if(leadAddMap.containsKey(oBuild.Full_Address__c))
            {
                building_lead__c OLead = new building_lead__c(Building_BL__c = oBuild.id , Building_Lead__c = leadAddMap.get(oBuild.Full_Address__c));
                OLead.name = string.valueof(oBuild.id) + string.valueof(leadAddMap.get(oBuild.Full_Address__c));
                OLeadlist.add(Olead);
            }
        }
        System.debug('OLeadlist'+OLeadlist);
        If(!OLeadlist.isEmpty())
        {
            upsert OLeadlist name;
        }
        
    }
    
    public static void UpdateLeadConverted(list<Lead> LeadList){
    
    // List Final     
    List<Task> TaskInsert = new List<Task>();
    unlinkBuilding(LeadList);
    
    for (Lead ld: LeadList){
        Task Tasks = new Task();
                
        if(Ld.IsConverted == true){
          Tasks.OwnerId 	= ld.OwnerId ; 
          Tasks.WhatId  	= ld.ConvertedAccountId ;  
          Tasks.Subject     = ld.Company ;  
            
          TaskInsert.add(Tasks);               
          system.debug('TaskTrigger' + TaskInsert);
               
         }
           
    }
        
    If(!TaskInsert.isEmpty()){          
       insert TaskInsert;       
    }
  }      
    
}