force-app/main/default/objects/Building__c/Building__c.object-meta.xml
<CustomObject>
    <label>Building</label>
    <nameField>
        <label>Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Suites__c/Suites__c.object-meta.xml
<CustomObject>
    <label>Suites</label>
    <nameField>
        <displayFormat>SU-{0000}</displayFormat>
        <label>Suite Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Suites</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Suites__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Suites</relationshipLabel>
    <relationshipName>Suites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Video__c/Video__c.object-meta.xml
<CustomObject>
    <label>Video</label>
    <nameField>
        <displayFormat>V-{0000}</displayFormat>
        <label>Videos Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Videos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Video__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Videos</relationshipLabel>
    <relationshipName>Videos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Video__c/fields/Suites__c.field-meta.xml
<CustomField>
    <fullName>Suites__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Suites</label>
    <referenceTo>Suites__c</referenceTo>
    <relationshipLabel>Videos</relationshipLabel>
    <relationshipName>Videos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/NewVideoControllerTest.cls
@isTest
private class NewVideoControllerTest {
    
    @isTest
    public static void getSuiteNameFromIdTest(){
        Building__c b= new Building__c(Name='test building');
        insert b;
        Suites__c s1 = new Suites__c();
        s1.Building__c = b.Id;
        Insert s1;
        Suites__c SuiteName = NewVideoController.getSuiteNameFromId(s1.Id);
        Suites__c s2 = [Select Id , Name from Suites__c ORDER BY CreatedDate DESC LIMIT 1];
        system.assertEquals(s2.Name, SuiteName.Name);
    }
    
     @isTest
    public static void saveVideoTest(){
        Building__c b= new Building__c(Name='test building');
        insert b;
        Suites__c s1 = new Suites__c();
        s1.Building__c = b.Id;
        Insert s1;
        Video__c video = new Video__c(Suites__c=s1.Id);
        NewVideoController.saveVideo(video);
    }
    
     @isTest
    public static void attachFileTest(){
        ContentVersion contentVersion = new ContentVersion(
                    Title          = 'ab picture',
                    PathOnClient   = 'Pic12.jpg',
                    VersionData    = Blob.valueOf('Test Content'),
                    IsMajorVersion = true);
            insert contentVersion;
        List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
        Building__c b= new Building__c(Name='test building');
        insert b;
        Suites__c s1 = new Suites__c();
        s1.Building__c = b.Id;
        Insert s1;
        Video__c video = new Video__c(Suites__c=s1.Id);
        insert video;
        
        
        if(documents.size()>0){
            NewVideoController.attachFile(video, documents[0].Id);
        }
    }

}