force-app/main/default/objects/Building__c/Building__c.object-meta.xml
<CustomObject>
    <label>Building</label>
    <nameField>
        <label>Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Floor_Plan__c/Floor_Plan__c.object-meta.xml
<CustomObject>
    <label>Floor Plan</label>
    <nameField>
        <displayFormat>FP-{0000}</displayFormat>
        <label>Floor Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Floor Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Floor_Plan__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Floor Plans</relationshipLabel>
    <relationshipName>Floor_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Floor_Plan__c/fields/Floor_Plan_Date__c.field-meta.xml
<CustomField>
    <fullName>Floor_Plan_Date__c</fullName>
    <label>Floor Plan Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Floor_Plan__c/fields/Floor_Plan_Type__c.field-meta.xml
<CustomField>
    <fullName>Floor_Plan_Type__c</fullName>
    <label>Floor Plan Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Original</fullName>
            </value>
            <value>
                <fullName>Scrubbed</fullName>
            </value>
            <value>
                <fullName>MA Branded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Floor_Plan__c/fields/Suites__c.field-meta.xml
<CustomField>
    <fullName>Suites__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Suites</label>
    <referenceTo>Suites__c</referenceTo>
    <relationshipLabel>Floor Plans</relationshipLabel>
    <relationshipName>Floor_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Suites__c/Suites__c.object-meta.xml
<CustomObject>
    <label>Suites</label>
    <nameField>
        <displayFormat>SU-{0000}</displayFormat>
        <label>Suite Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Suites</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Suites__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Suites</relationshipLabel>
    <relationshipName>Suites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Suites__c/fields/Floor_Plan__c.field-meta.xml
<CustomField>
    <fullName>Floor_Plan__c</fullName>
    <label>Floor Plan</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>No Plan Exists</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/NewFloorPlanControllerTest.cls
@isTest
public with sharing class NewFloorPlanControllerTest {
    @testSetup
    public static void testSetup(){
        Date d = Date.newInstance(2023,01,01);
        Floor_Plan__c fp = new Floor_Plan__c(Floor_Plan_Type__c='MA Branded', Floor_Plan_Date__c=d);
        insert fp;
        
        ContentVersion contentVersion = new ContentVersion(
        Title          = 'a picture',
        PathOnClient   = 'Pic.jpg',
        VersionData    = Blob.valueOf('Test Content'),
        IsMajorVersion = true);
        insert contentVersion;

        List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];

        ContentDocumentLink cdl = new ContentDocumentLink();
        cdl.LinkedEntityId = fp.Id;
        cdl.ContentDocumentId = documents[0].Id;
        cdl.ShareType = 'V';
        cdl.Visibility = 'AllUsers';
        insert cdl;
    }
    
    @isTest
    public static void getBuildingIdBySuiteIdTest(){
        Building__c b= new Building__c(Name='test building');
        insert b;
        Suites__c suite = new Suites__c(Building__c = b.Id);
        insert suite;
        String suiteId = NewFloorPlanController.getBuildingIdFromSuiteId(suite.Id);
        system.assert(suiteId != null);
        
    }
    
    @isTest
    public static void saveFloorPlanTest() {
        Date d = Date.newInstance(2023,01,01);
        Floor_Plan__c fp = new Floor_Plan__c(Floor_Plan_Type__c='MA Branded', Floor_Plan_Date__c=d);
        NewFloorPlanController.saveFloorPlan(fp);
        
        Floor_Plan__c[] fpList = [SELECT Id FROM Floor_Plan__c];
        system.Assert(fpList.size()>0);
    }
    
    @isTest
    public static void getContentDocumentByIdTest(){
        List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
        if(documents.size()>0){
            Id contentDocId = documents[0].Id;
            NewFloorPlanController.getContentDocumentById(contentDocId);
        }
        
    }
    
    @isTest
    public static void attachFileTest(){
        ContentVersion contentVersion = new ContentVersion(
                    Title          = 'ab picture',
                    PathOnClient   = 'Pic12.jpg',
                    VersionData    = Blob.valueOf('Test Content'),
                    IsMajorVersion = true);
            insert contentVersion;
        List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];

        Date d = Date.newInstance(2023,01,01);
        Floor_Plan__c fp = new Floor_Plan__c(Floor_Plan_Type__c='MA Branded', Floor_Plan_Date__c=d);
        insert fp;
        
        if(documents.size()>0){
            NewFloorPlanController.attachFile(fp, documents[0].Id);
        }
    }
    
    @isTest
    public static void getFloorPlanTypeValuesTest(){
        Map<String, String> pickListMap = new Map<String,String>();
        pickListMap = NewFloorPlanController.getFloorPlanTypeValues();
        system.Assert(pickListMap.size()>0);
    }
}