force-app/main/default/objects/Building__c/Building__c.object-meta.xml
<CustomObject>
    <label>Building</label>
    <nameField>
        <label>Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Building_Directory__c/Building_Directory__c.object-meta.xml
<CustomObject>
    <label>Directory Photo</label>
    <nameField>
        <displayFormat>BD-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Directory Photos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Building_Directory__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipName>Building_Directories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Building_Directory__c/fields/Date_Walked__c.field-meta.xml
<CustomField>
    <fullName>Date_Walked__c</fullName>
    <label>Date Walked</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Building_Directory__c/fields/Directory_Status__c.field-meta.xml
<CustomField>
    <fullName>Directory_Status__c</fullName>
    <label>Directory Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fully Vacant</fullName>
            </value>
            <value>
                <fullName>Future Building</fullName>
            </value>
            <value>
                <fullName>No Directory</fullName>
            </value>
            <value>
                <fullName>Secured Building</fullName>
            </value>
            <value>
                <fullName>Under Construction</fullName>
            </value>
            <value>
                <fullName>Walked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestDirectoryPhotoObjectTriggers.cls
@isTest
private class TestDirectoryPhotoObjectTriggers {
    
    @testSetup
    static void TestSetupCreateDirectoryPhotoAndContentDocumentObject()
    {
			Building__c	building1 = new Building__c();
        	building1.Name = 'TestBuilding';
        	insert building1;
       
        	building1 = [Select Id, Name from Building__c where Name = 'TestBuilding'];
        	Building_Directory__c Photo1 = new Building_Directory__c(Building__c=building1.Id);
        	Photo1.Building__c=building1.Id;
        	Photo1.Date_Walked__c=date.newInstance(2022,10,31);
        	Photo1.Directory_Status__c = 'Fully Vacant';
        	insert Photo1;
        
        	ContentVersion contentVersion = new ContentVersion(
                    						Title = 'a picture',
                    						PathOnClient   = 'Pic.jpg',
                    						VersionData    = Blob.valueOf('Test Content'),
                    						IsMajorVersion = true);
            insert contentVersion;
        
        	 ContentDocument document = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
        	 Photo1 = [Select Id from Building_Directory__c][0];
        	
        
        
        	//create ContentDocumentLink  record
            ContentDocumentLink cdl = new ContentDocumentLink();
            cdl.LinkedEntityId = Photo1.id;
            cdl.ContentDocumentId = document.Id;
            cdl.ShareType = 'V';
            cdl.Visibility = 'AllUsers';
            insert cdl; 
        	

}
    
     @isTest
    static void TestDeleteDirectoryPhotoObjectWhenDocumentDeleted()
    {
			ContentDocument testObjectContentDocument = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument][0];
        	 Database.DeleteResult result = Database.Delete(testObjectContentDocument, false);
    		 System.assert(result.isSuccess());
    }
    
    
     @isTest
    static void TestDeleteDocumentWhenDirectoryPhotoObjectrDeleted()
    {
        Building_Directory__c testObjectPhoto = [Select Id from Building_Directory__c][0];
        Database.DeleteResult result = Database.Delete(testObjectPhoto, false);
    	System.assert(result.isSuccess());
        
    }


}