force-app/main/default/objects/Building__c/Building__c.object-meta.xml
<CustomObject>
    <label>Building</label>
    <nameField>
        <label>Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Flyers__c/Flyers__c.object-meta.xml
<CustomObject>
    <label>Building Flyer</label>
    <nameField>
        <displayFormat>F-{0000}</displayFormat>
        <label>Flyer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Flyers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Flyers__c/fields/Active_or_Inactive__c.field-meta.xml
<CustomField>
    <fullName>Active_or_Inactive__c</fullName>
    <label>Active or Inactive</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Flyers__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipName>Flyers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Flyers__c/fields/Flyer_Date__c.field-meta.xml
<CustomField>
    <fullName>Flyer_Date__c</fullName>
    <inlineHelpText>Input date you received flyer from source</inlineHelpText>
    <label>Flyer Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Flyers__c/fields/Flyer_Type__c.field-meta.xml
<CustomField>
    <fullName>Flyer_Type__c</fullName>
    <label>Flyer Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Sublease</fullName>
            </value>
            <value>
                <fullName>Coworking</fullName>
            </value>
            <value>
                <fullName>Sale</fullName>
            </value>
            <value>
                <fullName>Direct and Sale</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestHandlerTriggerForFlyerInsert.cls
@isTest
private class TestHandlerTriggerForFlyerInsert {
    
    @testSetup
    static void TestSetupCreateFlyerDirectType()
    {
			Building__c	building1 = new Building__c();
        	building1.Name = 'TestBuilding';
        	insert building1;
       
        	building1 = [Select Id, Name from Building__c where Name = 'TestBuilding'];
        	Flyers__c Flyer1 = new Flyers__c(Building__c=building1.Id);
        	Flyer1.Flyer_Type__c='Direct';
        	Flyer1.Active_or_Inactive__c='Active';
        	Flyer1.Flyer_Date__c= Date.newInstance(2022,10,20);
        	insert Flyer1;
        
        	ContentVersion contentVersion = new ContentVersion(
                    						Title = 'a picture',
                    						PathOnClient   = 'Pic.jpg',
                    						VersionData    = Blob.valueOf('Test Content'),
                    						IsMajorVersion = true);
            insert contentVersion;
        
        	 ContentDocument document = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
        	Flyer1 = [Select Id from Flyers__c][0];
        	
        
        
        	//create ContentDocumentLink  record
            ContentDocumentLink cdl = new ContentDocumentLink();
            cdl.LinkedEntityId = Flyer1.id;
            cdl.ContentDocumentId = document.Id;
            cdl.ShareType = 'V';
            cdl.Visibility = 'AllUsers';
            insert cdl; 
        
        
           
        
        	
    }
    
   
    
    
    @isTest
    static void TestUpdateDirectFlyerStatus()
    {
      //TestSetupCreateFlyerDirectType();
      Building__c building2 = [Select Id, Name from Building__c where Name = 'TestBuilding'];
      Flyers__c Flyer2 = new Flyers__c(Building__c=building2.Id);
      Flyer2.Flyer_Type__c='Direct';
      Flyer2.Active_or_Inactive__c='Active';
      Flyer2.Flyer_Date__c= Date.newInstance(2022,10,30);
        //insert Flyer2;
      Database.SaveResult result = Database.insert(Flyer2, false);
      System.assert(result.isSuccess());
    }
    
   
     @isTest
    static void TestUpdateSaleFlyerStatus()
    {
      //TestSetupCreateFlyerSaleType();
      Building__c building2 = [Select Id, Name from Building__c where Name = 'TestBuilding'];
      Flyers__c Flyer2 = new Flyers__c(Building__c=building2.Id);
      Flyer2.Flyer_Type__c='Direct';
      Flyer2.Active_or_Inactive__c='Active';
      Flyer2.Flyer_Date__c= Date.newInstance(2022,10,14);
      //insert Flyer2;
      Database.SaveResult result = Database.insert(Flyer2, false);
      System.assert(result.isSuccess());
    }
    


}