force-app/main/default/objects/Building__c/Building__c.object-meta.xml
<CustomObject>
    <label>Building</label>
    <nameField>
        <label>Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Building__c/fields/Primary_Broker__c.field-meta.xml
<CustomField>
    <fullName>Primary_Broker__c</fullName>
    <label>Brokers</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Building_Brokers__c/Building_Brokers__c.object-meta.xml
<CustomObject>
    <description>To handle brokers related to buildings and tenants</description>
    <label>Listed Building</label>
    <nameField>
        <displayFormat>B{00000}</displayFormat>
        <label>Broker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Listed Buildings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Building_Brokers__c/fields/Broker__c.field-meta.xml
<CustomField>
    <fullName>Broker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Broker</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.Name</field>
            <operation>equals</operation>
            <value>Broker</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipName>BuildingBrokers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Building_Brokers__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Listing Brokers</relationshipLabel>
    <relationshipName>Brokers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/classes/TriggerOnBuildingBrokerHandler.cls
public class TriggerOnBuildingBrokerHandler {
    
    public static void updateBuildingPrimaryBroker(List<Building_Brokers__c> TriggerNew, Map<Id, Building_Brokers__c> oldMap){
        Set<String> buildingIds = new Set<String>();
        Set<String> brokerIds = new Set<String>();
        Map<String, String> buildingbrokerMap = new Map<String, String>();
        
        for(Building_Brokers__c bb : TriggerNew){
            buildingIds.add(bb.Building__c);
            brokerIds.add(bb.Broker__c);
            buildingbrokerMap.put(bb.Building__c, bb.Broker__c);
        }
        
        List<Contact> brokers = [Select Id,Name from Contact where Id =: brokerIds];
        Map<String, Contact> brokerMap = new Map<String, Contact>();
        
        for(Contact c : brokers){
            brokerMap.put(c.Id, c);
        }
        
        List<Building__c> buildings = [Select Id,Name,Primary_Broker__c from Building__c where Id =: buildingIds];
        
        for(Building__c bb : buildings){
            List<String> brokerNames = new List<String>();
            if(bb.Primary_Broker__c != null){
                brokerNames = bb.Primary_Broker__c.split(',');
            }
            Contact brok = brokerMap.get(buildingbrokerMap.get(bb.Id));
            brokerNames.add(brok.Id);
            Set<String> brokerUniqueNames = new Set<String>(brokerNames);
            bb.Primary_Broker__c = String.join(new List<String>(brokerUniqueNames), ',');
        }
        update buildings;
    }
}