force-app/main/default/objects/Building__c/Building__c.object-meta.xml
<CustomObject>
    <label>Building</label>
    <nameField>
        <label>Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Building_Photo__c/Building_Photo__c.object-meta.xml
<CustomObject>
    <label>Building Photo</label>
    <nameField>
        <displayFormat>BP-{00000}</displayFormat>
        <label>Building Photo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Building Photos</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Building_Photo__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Building Photos</relationshipLabel>
    <relationshipName>Building_Photos</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Building_Photo__c/fields/Building_Photo_Date__c.field-meta.xml
<CustomField>
    <fullName>Building_Photo_Date__c</fullName>
    <label>Building Photo Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/TestPhotoObjectTriggers.cls
@isTest
private class TestPhotoObjectTriggers {
    
     @testSetup
    static void TestSetupCreatePhotoAndContentDocumentObject()
    {
			Building__c	building1 = new Building__c();
        	building1.Name = 'TestBuilding';
        	insert building1;
       
        	building1 = [Select Id, Name from Building__c where Name = 'TestBuilding'];
        	Building_Photo__c Photo1 = new Building_Photo__c(Building__c=building1.Id);
        	Photo1.Building__c=building1.Id;
        	Photo1.Building_Photo_Date__c=date.newInstance(2022,10,31);
        	insert Photo1;
        
        	ContentVersion contentVersion = new ContentVersion(
                    						Title = 'a picture',
                    						PathOnClient   = 'Pic.jpg',
                    						VersionData    = Blob.valueOf('Test Content'),
                    						IsMajorVersion = true);
            insert contentVersion;
        
        	 ContentDocument document = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
        	Photo1 = [Select Id from Building_Photo__c][0];
        	
        
        
        	//create ContentDocumentLink  record
            ContentDocumentLink cdl = new ContentDocumentLink();
            cdl.LinkedEntityId = Photo1.id;
            cdl.ContentDocumentId = document.Id;
            cdl.ShareType = 'V';
            cdl.Visibility = 'AllUsers';
            insert cdl; 
        	

}
    
    
      @isTest
    static void TestDeletePhotoObjectWhenDocumentDeleted()
    {
			ContentDocument testObjectContentDocument = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument][0];
        	 Database.DeleteResult result = Database.Delete(testObjectContentDocument, false);
    		 System.assert(result.isSuccess());
    }
    
    @isTest
    static void TestDeleteDocumentWhenPhotoObjectrDeleted()
    {
        Building_Photo__c testObjectPhoto = [Select Id from Building_Photo__c][0];
        Database.DeleteResult result = Database.Delete(testObjectPhoto, false);
    	System.assert(result.isSuccess());
        
    }

    
    
    
}