force-app/main/default/objects/Building__c/Building__c.object-meta.xml
<CustomObject>
    <label>Building</label>
    <nameField>
        <label>Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Floor_Plan__c/Floor_Plan__c.object-meta.xml
<CustomObject>
    <label>Floor Plan</label>
    <nameField>
        <displayFormat>FP-{0000}</displayFormat>
        <label>Floor Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Floor Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Floor_Plan__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Floor Plans</relationshipLabel>
    <relationshipName>Floor_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Floor_Plan__c/fields/Floor_Plan_Date__c.field-meta.xml
<CustomField>
    <fullName>Floor_Plan_Date__c</fullName>
    <label>Floor Plan Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Floor_Plan__c/fields/Suites__c.field-meta.xml
<CustomField>
    <fullName>Suites__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Suites</label>
    <referenceTo>Suites__c</referenceTo>
    <relationshipLabel>Floor Plans</relationshipLabel>
    <relationshipName>Floor_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Suites__c/Suites__c.object-meta.xml
<CustomObject>
    <label>Suites</label>
    <nameField>
        <displayFormat>SU-{0000}</displayFormat>
        <label>Suite Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Suites</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Suites__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Suites</relationshipLabel>
    <relationshipName>Suites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Suites__c/fields/Floor_Plan__c.field-meta.xml
<CustomField>
    <fullName>Floor_Plan__c</fullName>
    <label>Floor Plan</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>No Plan Exists</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestFloorPlanTriggers.cls
@isTest
private class TestFloorPlanTriggers {
    
    @testSetup
    static void TestSetupCreateFloorPlanAndContentDocumentObject()
    {
			Building__c	building1 = new Building__c();
        	building1.Name = 'TestBuilding';
        	insert building1;
       
        	building1 = [Select Id, Name from Building__c where Name = 'TestBuilding'];
        	Suites__c Suites1 = new Suites__c(Building__c=building1.Id);
        	insert Suites1;
        
        	Floor_Plan__c floorPlan = new Floor_Plan__c(Suites__c=Suites1.Id,Floor_Plan_Date__c=date.newInstance(2022,12,19));
        	insert floorPlan;
            
        
        	ContentVersion contentVersion = new ContentVersion(
                    						Title = 'a picture',
                    						PathOnClient   = 'Pic.jpg',
                    						VersionData    = Blob.valueOf('Test Content'),
                    						IsMajorVersion = true);
            insert contentVersion;
        
        	 ContentDocument document = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
        	 floorPlan = [Select Id from Floor_Plan__c][0];
        	
        
        
        	//create ContentDocumentLink  record
            ContentDocumentLink cdl = new ContentDocumentLink();
            cdl.LinkedEntityId = floorPlan.id;
            cdl.ContentDocumentId = document.Id;
            cdl.ShareType = 'V';
            cdl.Visibility = 'AllUsers';
            insert cdl; 
        	
    }
    
      @isTest
    static void TestDeleteFloorPlanWhenDocumentDeleted()
    {
			ContentDocument testObjectContentDocument = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument][0];
        	 Database.DeleteResult result = Database.Delete(testObjectContentDocument, false);
    		 System.assert(result.isSuccess());
    }
    
    
    @isTest
    static void TestDeleteDocumentWhenFloorPlanDeleted()
    {
        Floor_Plan__c testObjectFloorPlan = [Select Id from Floor_Plan__c][0];
        Database.DeleteResult result = Database.Delete(testObjectFloorPlan, false);
    	System.assert(result.isSuccess());
        
    }
    

}