force-app/main/default/objects/Building__c/Building__c.object-meta.xml
<CustomObject>
    <label>Building</label>
    <nameField>
        <label>Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Building__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <label>Market (not used)</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StatePK__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Los Angeles</fullName>
            </value>
            <value>
                <fullName>Orange County</fullName>
            </value>
            <value>
                <fullName>San Francisco</fullName>
            </value>
            <value>
                <fullName>San Jose</fullName>
            </value>
            <value>
                <fullName>San Diego</fullName>
            </value>
            <value>
                <fullName>Ventura County</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Building__c/fields/Submarket__c.field-meta.xml
<CustomField>
    <fullName>Submarket__c</fullName>
    <label>Submarket (not used)</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Market__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>Burbank/Glendale/Pasadena</fullName>
            </value>
            <value>
                <fullName>Downtown Los Angeles</fullName>
            </value>
            <value>
                <fullName>Mid-Cities</fullName>
            </value>
            <value>
                <fullName>Mid-Wilshire</fullName>
            </value>
            <value>
                <fullName>San Fernando Valley</fullName>
            </value>
            <value>
                <fullName>San Gabriel Valley</fullName>
            </value>
            <value>
                <fullName>Santa Clarita Valley</fullName>
            </value>
            <value>
                <fullName>South Bay</fullName>
            </value>
            <value>
                <fullName>Southeast Los Angeles</fullName>
            </value>
            <value>
                <fullName>West Los Angeles</fullName>
            </value>
            <value>
                <fullName>Airport Area</fullName>
            </value>
            <value>
                <fullName>Central County</fullName>
            </value>
            <value>
                <fullName>North County</fullName>
            </value>
            <value>
                <fullName>South County</fullName>
            </value>
            <value>
                <fullName>West County</fullName>
            </value>
            <value>
                <fullName>SF 1</fullName>
            </value>
            <value>
                <fullName>SF 2</fullName>
            </value>
            <value>
                <fullName>SF 3</fullName>
            </value>
            <value>
                <fullName>SJ 1</fullName>
            </value>
            <value>
                <fullName>SJ 2</fullName>
            </value>
            <value>
                <fullName>SJ 3</fullName>
            </value>
            <value>
                <fullName>SD 1</fullName>
            </value>
            <value>
                <fullName>SD 2</fullName>
            </value>
            <value>
                <fullName>SD 3</fullName>
            </value>
            <value>
                <fullName>VC 1</fullName>
            </value>
            <value>
                <fullName>VC 2</fullName>
            </value>
            <value>
                <fullName>VC 3</fullName>
            </value>
            <value>
                <fullName>Hollywood/Wilshire Corridor</fullName>
            </value>
            <value>
                <fullName>Tri-Cities</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/City__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>HYPERLINK( &apos;/lightning/r/Market__c/&apos; + Submarket__r.Market__r.Id + &apos;/view&apos; ,  Submarket__r.Market__r.Name )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/City__c/fields/Submarket__c.field-meta.xml
<CustomField>
    <fullName>Submarket__c</fullName>
    <label>Submarket</label>
    <referenceTo>Submarket__c</referenceTo>
    <relationshipLabel>Cities</relationshipLabel>
    <relationshipName>Cities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Market__c/Market__c.object-meta.xml
<CustomObject>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Submarket__c/Submarket__c.object-meta.xml
<CustomObject>
    <label>Submarket</label>
    <nameField>
        <label>Submarket Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Submarkets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Submarket__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <label>Market</label>
    <referenceTo>Market__c</referenceTo>
    <relationshipLabel>Submarkets</relationshipLabel>
    <relationshipName>Submarkets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TestCityMapController.cls
@isTest
public class TestCityMapController {
    
    @isTest
    public static void TestBuildingsRelatedCity()
    {
		Market__c marketObj = new  Market__c(Name='test market');
       insert marketObj;
       
	   Submarket__c newSubMarketObj =   new  Submarket__c(Name='test Sub-market',Market__c= marketObj.Id);
       insert newSubMarketObj;
        
       City__c newCityObj = new City__c(Name='test City',Submarket__c= newSubMarketObj.Id);
       insert newCityObj;
        
       List<Building__c> allBuildings = CityMapController.buildingsRelatedCity(newCityObj.Id);
       
        
    }
    
     

}