force-app/main/default/objects/Rent_Schedule__c/Rent_Schedule__c.object-meta.xml
<CustomObject>
    <label>Rent Schedule</label>
    <nameField>
        <displayFormat>RS-{0000}</displayFormat>
        <label>Rent Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rent Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Rent_Schedule__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Rent Schedules</relationshipLabel>
    <relationshipName>Rent_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/NewRentSchedulesController.cls
public class NewRentSchedulesController {
    
    @AuraEnabled
    public static string getAccountNameFromId(Id accountId){
        
            String name = '';
            name = [SELECT Name FROM Account WHERE Id =: accountId].Name;
            return name;
        
    }
    
    @AuraEnabled
    public static Rent_Schedule__c saveRentSchedule( Rent_Schedule__c rentSchedule) {
        upsert rentSchedule;   
        return rentSchedule;   
    }
    
    @AuraEnabled
    public static Boolean CheckRentScheduleExists(String recordId)
    {
        
        List<Rent_Schedule__c> RentScheduleList = [Select Id,Name from Rent_Schedule__c where Account__c =:recordId]; 
        if(RentScheduleList.size()>0)
        {
			return true;
    	}  

       		return false;
    }
    

}