force-app/main/default/objects/Rent_Schedule__c/Rent_Schedule__c.object-meta.xml
<CustomObject>
    <label>Rent Schedule</label>
    <nameField>
        <displayFormat>RS-{0000}</displayFormat>
        <label>Rent Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rent Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Rent_Schedule__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Rent Schedules</relationshipLabel>
    <relationshipName>Rent_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rent_Schedule__c/fields/Data_Summary__c.field-meta.xml
<CustomField>
    <fullName>Data_Summary__c</fullName>
    <label>Data Summary</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Rent_Schedule__c/fields/Rent_per_Month__c.field-meta.xml
<CustomField>
    <fullName>Rent_per_Month__c</fullName>
    <label>Rent per Month</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Rents__c/Rents__c.object-meta.xml
<CustomObject>
    <label>Rent</label>
    <nameField>
        <displayFormat>R-{00000}</displayFormat>
        <label>Rent Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rent</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Rents__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Rent</relationshipLabel>
    <relationshipName>Rent1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Rents__c/fields/Rent_per_Month__c.field-meta.xml
<CustomField>
    <fullName>Rent_per_Month__c</fullName>
    <label>Rent per Month</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Rents__c/fields/Rent_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Rent_Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rent Schedule</label>
    <referenceTo>Rent_Schedule__c</referenceTo>
    <relationshipLabel>Rent</relationshipLabel>
    <relationshipName>Rent</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RemainingObligationController.cls
public class RemainingObligationController {
    
    @AuraEnabled
    public static List<Rents__c> getRelatedRentObj(String recordId)
    {       
        List<Rent_Schedule__c> RentScheduleList = [Select Id,Name from Rent_Schedule__c where Account__c =:recordId]; 
        List<Rents__c> rentObj = new List<Rents__c>();
        if(RentScheduleList.size()>0)
        {
			rentObj = [Select Rent_Start_Date__c,Rent_per_Month__c from Rents__c where Account__c=:recordId AND Rent_Schedule__c =:RentScheduleList[0].Id];
    	}  
       		return rentObj;  
    }
    
    
     @AuraEnabled
    public static List<Rent_Schedule__c> getRentScheduleSummary(String recordId)
    {
        
        List<Rent_Schedule__c> RentSchedule = new List<Rent_Schedule__c>();
        RentSchedule = [Select Id,Data_Summary__c,ReportsLinks__c from Rent_Schedule__c where Account__c =:recordId]; 
	    return RentSchedule;  		  
    }
    
      @AuraEnabled
    public static List<Rent_Schedule__c> getRentScheduleSummaryForRecordPage(String recordId)
    { 
        List<Rent_Schedule__c> RentSchedule = new List<Rent_Schedule__c>();
        RentSchedule = [Select Id,Data_Summary__c,ReportsLinks__c from Rent_Schedule__c where Id =:recordId]; 
	    return RentSchedule;     		  
    }
    @AuraEnabled
    public static void createReports(String recordId)
    {
        List<Rent_Schedule__c> RentScheduleList = [Select Id,Name from Rent_Schedule__c where Account__c =:recordId];
        String name = RentScheduleList[0].Name;
        MyReportCreator queueable = new MyReportCreator(name);
		System.enqueueJob(queueable);
   		  
    }

}