force-app/main/default/objects/Rent_Schedule__c/Rent_Schedule__c.object-meta.xml
<CustomObject>
    <label>Rent Schedule</label>
    <nameField>
        <displayFormat>RS-{0000}</displayFormat>
        <label>Rent Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rent Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Rent_Schedule__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Rent Schedules</relationshipLabel>
    <relationshipName>Rent_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rent_Schedule__c/fields/Rent_per_Month__c.field-meta.xml
<CustomField>
    <fullName>Rent_per_Month__c</fullName>
    <label>Rent per Month</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Rent_Schedule__c/fields/RS_End_Date__c.field-meta.xml
<CustomField>
    <fullName>RS_End_Date__c</fullName>
    <label>RS End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Rent_Schedule__c/fields/RS_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>RS_Start_Date__c</fullName>
    <label>RS Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/TestRentScheduleController.cls
@isTest
private class TestRentScheduleController {
    
    @isTest
    public static void testGetAccountName()
    {
        Account acc = new Account(Name = 'Test Account');
        Insert acc;
        String Name = NewRentSchedulesController.getAccountNameFromId(acc.Id);
        System.assertEquals('Test Account', Name, 'Name should be equal');
    }
    
     @isTest
    public static void testSaveRentSchedule()
    {
        Account acc = new Account(Name = 'Test Account');
        Insert acc;
        Rent_Schedule__c newRent = new Rent_Schedule__c(Account__c = acc.Id,
                                                        RS_Start_Date__c = date.newInstance(2023,01,31),
                                                        RS_End_Date__c = date.newInstance(2023,12,31),
                                                       Rent_per_Month__c = Decimal.valueOf('100'));
        Rent_Schedule__c rent = NewRentSchedulesController.saveRentSchedule(newRent);
        System.assertEquals(newRent, rent, 'Object should be equal');
    }
    
     @isTest
    public static void TestCheckRentScheduleExists()
    {
        Account acc = new Account(Name = 'Test Account');
        Insert acc;
        Rent_Schedule__c newRent = new Rent_Schedule__c(Account__c = acc.Id,
                                                        RS_Start_Date__c = date.newInstance(2023,01,31),
                                                        RS_End_Date__c = date.newInstance(2023,12,31),
                                                       Rent_per_Month__c = Decimal.valueOf('100'));
        Insert newRent;       
        System.assertEquals(NewRentSchedulesController.CheckRentScheduleExists(acc.Id), true, 'Value Should be true.');
    }

}