force-app/main/default/objects/Rent_Schedule__c/Rent_Schedule__c.object-meta.xml
<CustomObject>
    <label>Rent Schedule</label>
    <nameField>
        <displayFormat>RS-{0000}</displayFormat>
        <label>Rent Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rent Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Rent_Schedule__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Rent Schedules</relationshipLabel>
    <relationshipName>Rent_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rent_Schedule__c/fields/Rent_per_Month__c.field-meta.xml
<CustomField>
    <fullName>Rent_per_Month__c</fullName>
    <label>Rent per Month</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Rent_Schedule__c/fields/RS_End_Date__c.field-meta.xml
<CustomField>
    <fullName>RS_End_Date__c</fullName>
    <label>RS End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Rent_Schedule__c/fields/RS_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>RS_Start_Date__c</fullName>
    <label>RS Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/TestNewRentSchedulesController.cls
@isTest
private class TestNewRentSchedulesController {
    
	@isTest
    public static void getAccountNameByIdTest(){
        Account b= new Account(Name='test Account');
        insert b;
        String AccountName = NewRentSchedulesController.getAccountNameFromId(b.Id);
        system.assertEquals('test Account', AccountName);
    }
    
    @isTest
    public static void TestInsertRentSchedule()
    {
        Account newacc = new Account(Name='test Account');
        insert newacc;
        Rent_Schedule__c newRS = new Rent_Schedule__c(Account__c=newacc.Id,
                                                      RS_Start_Date__c=date.newInstance(2023,01,01),
                                                      RS_End_Date__c=date.newInstance(2023,12,31),
                                                      Rent_per_Month__c=decimal.valueof('10')
                                                               		);
        NewRentSchedulesController.saveRentSchedule(newRS);
    }
}