force-app/main/default/objects/Rent_Schedule__c/Rent_Schedule__c.object-meta.xml
<CustomObject>
    <label>Rent Schedule</label>
    <nameField>
        <displayFormat>RS-{0000}</displayFormat>
        <label>Rent Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rent Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Rent_Schedule__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Rent Schedules</relationshipLabel>
    <relationshipName>Rent_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RentScheduleListController.cls
public with sharing class RentScheduleListController {
    
     @AuraEnabled 
    public static List<Rent_Schedule__c> getAllRSByAccountId(String accountId){
        
            List<Rent_Schedule__c> RSList = [SELECT Id, Name FROM Rent_Schedule__c WHERE Account__c =:accountId];
            return RSList;
        
    }
    
     @AuraEnabled
    public static string getAccountNameFromId(Id accountId){
        
            String name = '';
            name = [SELECT Name FROM Account WHERE Id =: accountId].Name;
            return name;
        
    }
    
    @AuraEnabled
    public static Boolean deleteRS(String recordId) {
        Rent_Schedule__c RSObj = [SELECT Id, Name FROM Rent_Schedule__c WHERE Id =:recordId];
        delete RSObj;   
        return true;
        
    }

}