force-app/main/default/objects/Flyer_Account__c/Flyer_Account__c.object-meta.xml
<CustomObject>
    <label>Flyer-Account</label>
    <nameField>
        <label>Flyer-Suite Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flyer-Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Flyer_Account__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Flyers</relationshipLabel>
    <relationshipName>Flyer_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Flyer_Account__c/fields/Building_Flyer__c.field-meta.xml
<CustomField>
    <fullName>Building_Flyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Building Flyer</label>
    <referenceTo>Flyers__c</referenceTo>
    <relationshipLabel>Flyers</relationshipLabel>
    <relationshipName>Flyer_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Flyer_Suite__c/Flyer_Suite__c.object-meta.xml
<CustomObject>
    <label>Flyer-Suite</label>
    <nameField>
        <label>Flyer-Suite Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flyer-Suites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Flyer_Suite__c/fields/Building_Flyer__c.field-meta.xml
<CustomField>
    <fullName>Building_Flyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Building Flyer</label>
    <referenceTo>Flyers__c</referenceTo>
    <relationshipLabel>Flyer</relationshipLabel>
    <relationshipName>Flyer_Suites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Flyer_Suite__c/fields/Suites__c.field-meta.xml
<CustomField>
    <fullName>Suites__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Suites</label>
    <referenceTo>Suites__c</referenceTo>
    <relationshipLabel>Flyers</relationshipLabel>
    <relationshipName>Flyer_Suites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Suites__c/Suites__c.object-meta.xml
<CustomObject>
    <label>Suites</label>
    <nameField>
        <displayFormat>SU-{0000}</displayFormat>
        <label>Suite Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Suites</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Suites__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Suites</relationshipLabel>
    <relationshipName>Suites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FlyersRelatedListController.cls
public with sharing class FlyersRelatedListController {
    @AuraEnabled
    public static List<Account> getFlyerRelatedAccountsById(String flyerId){
        try {
            List<Flyer_Account__c> flyerAccounts = [SELECT 	Account__c, Building_Flyer__c FROM Flyer_Account__c WHERE Building_Flyer__c =:flyerId];
            List<Id> accountIds = new List<Id>();
            for(Flyer_Account__c flyerAccount : flyerAccounts){
                accountIds.add(flyerAccount.Account__c);
            }

            List<Account> listAccount = [SELECT Name FROM Account WHERE Id IN: accountIds];
            return listAccount;
        } catch (Exception e) {
            system.debug(e);
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static List<Suites__c> getFlyerRelatedSuitesById(String flyerId){
        try {
            List<Flyer_Suite__c> flyerAccounts = [SELECT 	Suites__c, Building_Flyer__c FROM Flyer_Suite__c WHERE Building_Flyer__c =:flyerId];
            List<Id> suiteIds = new List<Id>();
            for(Flyer_Suite__c flyerAccount : flyerAccounts){
                suiteIds.add(flyerAccount.Suites__c);
            }

            List<Suites__c> listAccount = [SELECT Name FROM Suites__c WHERE Id IN: suiteIds];
            return listAccount;
        } catch (Exception e) {
            system.debug(e);
            throw new AuraHandledException(e.getMessage());
        }
    }
}